packages/arcgis-rest-geocoder/src/geocoder.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts
packages/arcgis-rest-items/test/mocks/item.ts
packages/arcgis-rest-items/test/mocks/resources.ts
packages/arcgis-rest-items/test/mocks/search.ts

* fixed updateItem() to make passing authentication mandatory
* simplified a few other existing methods that already default to POST
* added new methods
* `getItemResources`
* `updateItemResource`
* `removeItemResource`
* in test suite, broke out item responses into multiple files

adding three more item resource methods

---

CHANGELOG.md
demos/express/package.json
demos/geocoder/package.json
demos/vanilla/package.json
lerna.json
package.json
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
support/changelog.js
support/publish.sh

While testing release automation I accidentally published v1.0.1 to NPM. This PR updates all teh necessary files. Once this gets merged I'll publish 1.0.2 and deprecate 1.0.1 to finish cleaning stuff up.

Fix more release automation issues

---

README.md
docs/src/api/_declaration.html
package.json
packages/arcgis-rest-auth/README.md
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-common-types/README.md
packages/arcgis-rest-geocoder/README.md
packages/arcgis-rest-groups/README.md
packages/arcgis-rest-items/README.md
packages/arcgis-rest-request/README.md

fixes a few dozen dead links within the page body of individual declarations.
after selectively staging a few files and running `npm run c` i noticed that it bundles its own `git add --all` command. i think it'd be preferable if it didn't.
also including READMEs to resolve #81 and fixed a couple typos

docs(fix dead links): fixed broken links within declaration page content

---

docs/src/api/_layout.html
docs/src/js/api-search.js

STR:
1. launch https://esri.github.io/arcgis-rest-js/api/
2. search for `h` and select `HTTPMethods` from the list of suggestions
if anyone has a more _elegant_ solution than checking `window.location.origin` in a Vue component, i'm all 👂 s

prepend base url to API reference search results

---

.travis.yml
package.json

second attempt at #88 
it seems more appropriate to only have travis build the doc and push updates to the live site when a release is tagged.
this will require us to update the site manually when a doc bug has been patched. but i think this is preferable to having new API documentation land too soon.

have travis push doc updates when a release is tagged

---

.coveralls.yml
.travis.yml
README.md
karma.conf.js
package-lock.json
package.json

this PR gets headless chrome tests running on travis and should hook up a coveralls integration.
i had trouble with the relevant encrypted environment variables when i tested against [my fork](https://github.com/jgravois/arcgis-rest-js/pull/1), but i figured i'd take one more crack at it. 
ref: https://coveralls.io/github/Esri/arcgis-rest-js

hook up coveralls

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/check-for-errors.ts

ISSUES CLOSED: #92 
Removes the in-comment links for now. If we are going to have in-comment links in the future, it will have to be in a way that allows injecting a base url so it works locally and on the github pages.

docs(links): fix remaining 404s in docs

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

window.parent is equal to itself when there is no parent (see https://developer.mozilla.org/en-US/docs/Web/API/Window/parent), so it will always be truthy. Need to check
that the window has a separate parent instead.
Currently, if you set `popup` to false when doing oauth through the UserSession, you'll get an error when calling `completeOauth2` because it tries to run 
```
win.parent[`__ESRI_REST_AUTH_HANDLER_${clientId}`](error, oauthInfo);
```
at [UserSession:342](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-auth/src/UserSession.ts#L342)

fix(oauth): check for window parent correctly in oauth without popup

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

throw ArcGISAuthError instead of Error when unable to refresh a token

---

demos/ago-node-cli/README.md
demos/ago-node-cli/ago.js
demos/ago-node-cli/index.js
demos/ago-node-cli/lib/item-export-command.js
demos/ago-node-cli/lib/item-search-command.js
demos/ago-node-cli/package-lock.json
demos/ago-node-cli/package.json

Demo that shows how to use arcgis-rest-js in a node cli application.
Provides two simple example commands - search items, and export an item to file.
Open to any other ideas / comments / zomg-you-did-wat?!!?

Node CLI Example

---

packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts

ISSUES CLOSED: #118
Looks like a bunch of prettier changes as well, but see https://github.com/Esri/arcgis-rest-js/compare/master...fix-118#diff-9ee3f9eab7eb2404aac1291267c3916bL333 for what was changed.

Flip param values in updateItemResource so they are passed correctly

---

packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts

ISSUES CLOSED: #117 
to be honest, mixing in a properly serialized item like this seems a little _strange_.
```ts
requestOptions.params = {
...requestOptions.params,
...serializeItem(requestOptions.item)
};
```

fix(items): dont override user supplied parameters when updating items

---

CHANGELOG.md
support/changelog.js

changelog.js had some formatting issues in the 1.0.3 release (see https://github.com/Esri/arcgis-rest-js/blob/master/CHANGELOG.md#103---december-21st-2017)
This occurred because it pulled all text after `ISSUES CLOSED:` and put it into the issue link. Commit https://github.com/Esri/arcgis-rest-js/commit/29e01897e35c6c4bb02709998afe2c493401d86d was the one that caused the formatting issue because it had lots of text after the closed issues list.
This PR makes changelog.js discard all text after the newline, so it only pulls the comma-separated issues.

chore(changelog): prevent changelog.js from looking beyond newline for closed issues

---

demos/batch-geocoder-node/package-lock.json
packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-geocoder/src/geocoder.ts
packages/arcgis-rest-groups/src/groups.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts
packages/arcgis-rest-items/test/mocks/item.ts
packages/arcgis-rest-items/test/mocks/search.ts
packages/arcgis-rest-request/src/utils/ArcGISAuthError.ts
packages/arcgis-rest-request/src/utils/ArcGISRequestError.ts
packages/arcgis-rest-request/src/utils/get-portal.ts
packages/arcgis-rest-request/test/utils/get-portal-url.test.ts
tslint.json

porting a whole load of interfaces and types originally written by @JeffJacobson :tada: 
batch-geocoder
BREAKING CHANGE:
no longer prefacing interface names with an `I`
maybe its just the ArcObjects phobia talking, but 5 minutes into this port i started to agree with [@tomwayson](https://github.com/Esri/arcgis-rest-js/issues/107#issuecomment-367217416). A quick look at the TypeScript Language [Specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#7.1) made it clear that its not a universally agreed upon convention.
i'm planning on tackling #104 soon so it makes sense to me to rip off the proverbial esri-loader band-aid here too and just …

add more common types

---

packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/request.test.ts

I think this is a pretty elegant solution to the debate we've been having in #66 if I do say so myself. I think we let the consumer specify the limit. Only if they pass `httpMethod: 'GET'` _and_ the new `maxUrlLength: charLimitForMyBrowserOrServer`, will it switch to 'POST' if the limit is exceeded. That gets us off the hook for maintaining a limit.
resolves #66

let consumers specify GET w/ max URL length; if exceeded, use POST

---

demos/ago-node-cli/README.md
demos/geocoder-browser/index.html
rollup.config.umd.js

Close #128.
@tomwayson @jgravois I did verify that this makes bundles smaller but you should verify that the demos still work. I probably inadvertently removed this while setting up the build system.

Set externals properly for UMD builds

---

packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/request.test.ts

check for errors before trying to parse response

---

packages/arcgis-rest-geocoder/src/geocoder.ts
packages/arcgis-rest-geocoder/test/geocoder.test.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/check-for-errors.ts
packages/arcgis-rest-request/test/utils/check-for-errors.test.ts

and set up previous method to be deprecated in next major release
ISSUES CLOSED: #122

refactor(geocoder): use a more descriptive method to fetch metadata

---

.vscode/settings.json
package-lock.json
package.json
packages/arcgis-rest-request/src/utils/process-params.ts
packages/arcgis-rest-request/test/utils/process-params.test.ts

ISSUES CLOSED: #142 
don't ask me why i had to add two flags with [default values](https://prettier.io/docs/en/options.html) to get prettier to _stop_ re-indenting every line in all the files i was editing.
i. have. no. idea.

fix(request): ensure falsy request parameters like zero are passed through

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

in testing #140 i noticed that _sometimes_ my username was being reported as `jgravois&persist=true` when i ticked <kbd>Keep me signed in</kbd>
this regex ensures that additional parameters aren't appended to usernames accidentally when they are present by swapping in a match block that accepts _anything_ except an `&`.
> TIL: ArcGIS Organizational usernames and passwords **can** include special characters now!

fix(auth): better regex match for usernames

---

packages/arcgis-rest-feature-service/src/features.ts
packages/arcgis-rest-feature-service/test/features.test.ts

Looks like I noticed `IFeatureSet` in common types before, but forgot to use it.

Fix incorrect types in arcgis-rest-feture-service and get branch coverage back to 100%

---

packages/arcgis-rest-request/src/utils/process-params.ts
packages/arcgis-rest-request/test/utils/process-params.test.ts

ISSUES CLOSED: #142 
i fully grant there may be a tidier way to do this. 
if we were to test for `params.hasOwnProperty(key)` like we do in Esri Leaflet, we wouldn't be able to handle { "foo": null }

fix(request): ensure request is passed through as a request parameter

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

Usernames with @ symbols are returned from OAuth as %40, so we need to decode them with
decodeURIComponent.
ISSUES CLOSED: #165

fix(auth): decode username when parsing response from OAuth

---

packages/arcgis-rest-auth/src/authenticated-request-options.ts
packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-users/README.md
packages/arcgis-rest-users/package.json
packages/arcgis-rest-users/src/index.ts
packages/arcgis-rest-users/src/users.ts
packages/arcgis-rest-users/test/mocks/responses.ts
packages/arcgis-rest-users/test/users.test.ts
packages/arcgis-rest-users/tsconfig.json

* didnt implement `getSelf()` because it'd cause a global namespace collision, but the following three signatures are supported
```js
getUser("johnqpublic")
// returns info available to anonymous requests
getUser({ authentication: session })
// returns information about the currently logged in user
getUser({
authentication: session,
username: "otheruser"
})
// returns information about an explicitly defined user (based on level of permission of the authenticated session)
```
ISSUES CLOSED: #159

feat(new users package): add rest-users with a single method

---

.gitignore
demos/oauth2-browser/authenticate.html
demos/oauth2-browser/config.js.template
demos/oauth2-browser/index.html
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

In porting [`torii-provider-arcgis`](https://github.com/dbouwman/torii-provider-arcgis/) to use this lib i realized that we are missing support for a couple useful parameters exposed by [oauth2/authorize?](https://developers.arcgis.com/rest/users-groups-and-items/authorize.htm)
* locale - The locale assumed to render the login page.
* state - An opaque value used by applications to maintain state between authorization requests and responses.
@esri/arcgis-rest-demo-vanilla

fix(OAuth2 options): add 'locale' and 'state' parameters for browser based OAuth2

---

docs/src/guides/babel-and-rollup.md
docs/src/guides/babel-and-webpack.md
docs/src/guides/from-a-cdn.md
docs/src/guides/node.md

found a few `404`s ripping off this doc site for [`@esri/hub.js`](https://github.com/Esri/hub.js/pull/12)

fix bad link in the guides

---

.travis.yml

6.x moved into [maintenance mode](https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742) on 4/30/2018

have travis test on Node 8/10 (instead of 6/8)

---

packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts
packages/arcgis-rest-request/src/request.ts

fix(IItem): make id and owner the only required properties of IItem

---

packages/arcgis-rest-geocoder/src/geocoder.ts
packages/arcgis-rest-geocoder/test/geocoder.test.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts

@noahmulfinger noticed `searchItems()` in #183. `geocode()` had the same problem.

make sure methods w/ union types pass through *all* requestOptions

---

packages/arcgis-rest-request/src/request.ts

to support Integrated Windows Authentication.
ref: https://github.com/Esri/torii-provider-arcgis/pull/43

fix(fetch): set credentials: 'same-origin' in fetch options 

---

packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-users/package.json
umd-base-profile.js
umd-production-profile.js

remove `arcgis-rest-` from built .umds
old: https://unpkg.com/@esri/arcgis-rest-request/dist/umd/arcgis-rest-request.umd.js
new: https://unpkg.com/@esri/arcgis-rest-request/dist/umd/request.umd.js

more concise .umd filenames

---

demos/oauth2-browser/authenticate.html
demos/oauth2-browser/index.html
package-lock.json
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

IE and Edge will throw errors for any non-string object that comes from another frame or window. In this case passing the date object from the oauth popup window back to the main window will result in `Permission denied` errors when trying to access `tokenExpires` which will result in errors when actually trying to use this for a request.
The solution is to `JSON.stringify` everything that crosses the window boundary and `JSON.parse` it on the other end.

Oauth ie edge fix

---

docs/acetate.config.js

no code is necessary to resolve the problem reported in #198. we just need to push something into `master` to convince lerna to help us publish a `v1.2.1` release.
ISSUES CLOSED: #198 

fix(umd): strip outdated umd files from npm packages

---

packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts

Hi all. I'm just getting started using `arcgis-rest-js` to automate some tooling (let CI upload new WAB Widgets to our Portal upon successful PR merge) and got snagged on a small issue: [The documentation](https://esri.github.io/arcgis-rest-js/api/common-types/IItem/) shows the `typeKeywords` and `tags` properties of an `IItem` to be optional, however the serializer method expects them to be an array. If they are omitted from an `item` object a `Cannot read property 'join' of undefined` error will be thrown ([ex](https://stackblitz.com/edit/js-pmfwlq?embed=1&file=index.js&hideExplorer=1&hideNavigation=1)).  I think this fix would resolve the issue. I can generate a test if need-be.
Is there any particular reason we have `strictNullChecks: false` in the `tsconfig.json`? I believe this …

Handle missing tags and typeKeywords properties

---

packages/arcgis-rest-geocoder/README.md

for the problem above, see https://github.com/badges/shields/issues/1732

fix title in geocoder readme

---

demos/feature-service-browser/index.html
demos/geocoder-browser/index.html
demos/jsapi-integration/README.md
demos/jsapi-integration/index.html
demos/jsapi-integration/package-lock.json
demos/jsapi-integration/package.json
docs/acetate.config.js
docs/src/guides/amd-requirejs-dojo.md
docs/src/guides/from-a-cdn.md
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

first pass at #208
PRing against the `amd` branch for the sake of the demo.
```js
require([
"@esri/arcgis-rest-auth",
"@esri/arcgis-rest-items",
"esri/identity/IdentityManager",
"esri/WebMap"
], function(
arcgisAuth, arcgisItems, esriId, WebMap
) {
const session = new arcgisAuth.UserSession({
username: "arcgis_python",
password: "P@ssword123"
});
// https://geosaurus.maps.arcgis.com/home/item.html?id=728043ac6a574a00b8f1cd5ee0eae8cd
arcgisItems.getItemData("728043ac6a574a00b8f1cd5ee0eae8cd", { authentication: session })
.then(response => {
esriId.registerToken(session.getCredential());
new WebMap({
portalItem: {
// dig the webmap id out of the response
id: response.map.itemId
}
});
});
});
```

add UserSession.getCredential()

---

demos/jsapi-integration/README.md
demos/jsapi-integration/index.html

don't load arcgis-rest-js using dojo
call require() _after_ loading item
@esri/jsapi-integration

docs(demos): jsapi integration demo shows more typical scenario

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

to support passing arcgis-rest-js and jsapi credentials back and forth
ISSUES CLOSED: #208

feat(auth): toCredential/fromCredential

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

`www` _4 lyfe_.
ISSUES CLOSED: #223

fix(auth): use www.arcgis.com consistently

---

demos/jsapi-integration/index.html
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

resolves #208 once and for all (i hope)
tested against www.arcgis.com _and_ ArcGIS Enterprise.

convert JSAPI credentials to a _valid_ UserSession 

---

docs/src/api/_package.html
docs/src/api/index.html
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

fix to ensure we throw an error when a developer attempts to fetch a token for a standalone instance of ArcGIS Server that doesn't advertise an `owningSystemUrl` (like [this one](http://sampleserver6.arcgisonline.com/arcgis/rest/info?f=json)).
STR:
```js
const session = new arcgisRest.UserSession({
username: "johnq",
password: "public"
});
session.getToken("http://sampleserver6.arcgisonline.com/arcgis/rest/services/")
.catch(err => {
err.code // "NOT_FEDERATED"
})
```

throw NOT_FEDERATED error when no 'owningSystemUrl' is found

---

packages/arcgis-rest-auth/package.json

The wrong package name makes it impossible to install since that dep cannot be installed.

Fix peer dependency name

---

packages/arcgis-rest-feature-service/src/add.ts
packages/arcgis-rest-feature-service/src/delete.ts
packages/arcgis-rest-feature-service/src/update.ts
packages/arcgis-rest-feature-service/test/features.test.ts

working on https://github.com/Esri/hub.js/pull/35 i noticed that we're currently unnecessarily passing a few unrecognized parameters (`adds=`, `updates=`, `deletes=`) in requests.
```js
deleteFeatures({
url,
deletes: [123]
})
```
its a harmless bug, but its one i introduced.
while i was at it, i also fixed the corresponding tests to introspect the objects returned by each promise instead of the canned responses we feed to the mock server.

fix: ensure deleteFeatures doesnt pass the extraneous parameter 'deletes'

---

packages/arcgis-rest-auth/package.json
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/package.json

> this PR description has been edited _heavily_. previous drafts are available from the <kbd>edited &#9660;</kbd> dropdown 
proposed fix to enable the generation of tokens for ArcGIS Data Store content associated with ArcGIS Enterprise.
the tweak i'm proposing ~~generalizes the comparison of the two relevant urls and gives a ✅ as long as the portal and service url share the same `sub.domain.com`.~~ introspects the current session to see whether a token is already available. if not, and both username/password are present (indicating that the session was _not_ instantiated for an OAuth flow), then a request to fetch one manually is fired.
STR:
```js
// real portal instance, fake username and password
const session = new UserSession({
username: "c@sey",
password: "jones",
portal: …
```

fix(enterprise): ensure a brand new token can be generated for servers federated with ArcGIS Enterprise

---

packages/arcgis-rest-users/src/users.ts
packages/arcgis-rest-users/test/users.test.ts

fix(users): users defaults to https://www.arcgis.com instead of http://

---

packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-common-types/src/index.js
packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-groups/src/groups.ts
packages/arcgis-rest-groups/test/mocks/responses.ts
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/package.json

this PR:
* removes the `IGroup` interface from 'arcgis-rest-groups' (in favor of the one in 'arcgis-rest-common-types').
* updates the canonical interface to extend `IItem` (instead of duplicating props)
* updates the canonical interface with the new props @alukach mentioned
sorry for the noise in the diff, when @tomwayson published `v1.5.1` for some reason the script didn't update all the relevant package.json files.

IGroup cleanup

---

packages/arcgis-rest-common-types/src/group.ts
packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-common-types/src/item.ts
packages/arcgis-rest-groups/src/groups.ts
packages/arcgis-rest-groups/test/mocks/responses.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/mocks/item.ts
packages/arcgis-rest-items/test/mocks/search.ts
packages/arcgis-rest-users/test/mocks/responses.ts

resolves #246:
* adds a couple code snippets
* ~~stops using the (unnecessary) interface `IUserRequestOptions`~~
* `createItem()` now requires an Item with 'title' and 'type'
* `updateItem()` now requires an Item with an 'id'
* ~~the methods above, and `removeItem()`, now _all_ require authentication~~
no one loves interface soup more than @dbouwman. hopefully he can find time to review soon as @tomwayson is out until late next week.

constrain what constitutes a valid Item for crud operations, and require auth

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-request/src/request.ts

docs: clarify that createItemInFolder expects an id, not a name.

---

packages/arcgis-rest-feature-service/src/addAttachment.ts
packages/arcgis-rest-feature-service/src/deleteAttachments.ts
packages/arcgis-rest-feature-service/src/getAttachments.ts
packages/arcgis-rest-feature-service/src/updateAttachment.ts

@jgravois I noticed the the Notes in the API docs come from the comments in the interfaces themselves and not from `@param`. Here they be.

Add attachment notes for api docs

---

demos/attachments/package-lock.json
packages/arcgis-rest-feature-service/src/query.ts

`count` and `extent` properties can be returned depending on input params. See examples here https://developers.arcgis.com/rest/services-reference/query-feature-service-layer-.htm
I didn't include this in this PR, but technically `features` should also be optional in the response type. I didn't want to edit `IFeatureSet` since it makes sense that `features` would be required there, so I just left it.

fix(query features): add count and extent to IQueryFeaturesResponse

---

packages/arcgis-rest-feature-service/test/attachments.test.ts
packages/arcgis-rest-items/src/items.ts
packages/arcgis-rest-items/test/items.test.ts
packages/arcgis-rest-request/src/utils/encode-form-data.ts
packages/arcgis-rest-request/src/utils/process-params.ts
packages/arcgis-rest-request/test/utils/encode-form-data.test.ts

For reasonable browsers, a Blob can be converted into a File and sent up with its filename. For IE 11 & Edge, the File constructor is not available, and even if one adds the missing File properties to the Blob, it's sent up to AGOL as "blob" by these two browsers. Changing encode-form-data to use the filename in the FormData.append call gets past this behavior.
I changed the name of IItemJsonDataRequestOptions from a documentation perspective since it can be used by both the JSON and binary functions.
Working on test code.

Add support for uploading blob item's data

---

demos/geocoder-browser/index.html
demos/geocoder-browser/post-sign-in.html
packages/arcgis-rest-geocoder/src/index.ts

@esri/arcgis-rest-geocoder-vanilla
ISSUES CLOSED: #267

fix: ensure getGeocodeService() is exported

---

demos/batch-geocoder-node/batch-geocode.js
demos/batch-geocoder-node/package-lock.json
demos/batch-geocoder-node/package.json
packages/arcgis-rest-auth/src/ApplicationSession.ts
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/src/fetch-token.ts
packages/arcgis-rest-auth/src/generate-token.ts
packages/arcgis-rest-auth/test/fetchToken.test.ts
packages/arcgis-rest-auth/test/generateToken.test.ts
packages/arcgis-rest-request/src/request.ts

i have no idea _why_, but `ember-fetch` ignores the real [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) we currently pass through. this approach is also necessary to support the use case described in #203.
i can't see any downside to the proposed change, but i'm happy to be proven wrong.

refactor: use JSON object literal to construct Headers

---

packages/arcgis-rest-feature-service/src/helpers.ts
packages/arcgis-rest-feature-service/src/index.ts
packages/arcgis-rest-feature-service/src/queryRelated.ts
packages/arcgis-rest-feature-service/test/features.test.ts
packages/arcgis-rest-feature-service/test/mocks/feature.ts

Hey arcgis-rest-js team!
`queryRelatedRecords` came up in a project so I thought I'd try TS and write a wrapper--please let me know if you have feedback/suggested changes
Also, how do I compile and test the function? I wrote a couple mock [unit tests](https://github.com/mpayson/arcgis-rest-js/blob/mp-queryrelates/packages/arcgis-rest-feature-service/test/features.test.ts#L175) following the `queryFeatures` [pattern](https://github.com/mpayson/arcgis-rest-js/blob/mp-queryrelates/packages/arcgis-rest-feature-service/test/features.test.ts#L45), but I'm not sure how to access this function to test on a live feature service
thanks!
cc @jgravois

Query related records

---

demos/batch-geocoder-node/README.md
demos/batch-geocoder-node/config-template.js
demos/batch-geocoder-node/package-lock.json
demos/batch-geocoder-node/package.json
demos/express/package-lock.json
demos/express/package.json
package-lock.json

https://nvd.nist.gov/vuln/detail/CVE-2018-3721
batch-geocoder
@esri/arcgis-rest-demo-express

chore(:lock:): bump devDependencies to resolve security vulnerability

---

packages/arcgis-rest-items/src/search.ts
packages/arcgis-rest-items/test/search.test.ts

this will allow us to _fake_ an authenticated session in ArcGIS Hub by passing in a token manually.
```js
searchItems({
searchForm: { q: "DC AND typekeywords:hubSiteApplication" },
params: { token: "fake" }
})
```

Fix: ensure searchItems mixes in parameters and the provided form

---

packages/arcgis-rest-feature-service/src/add.ts

Remove duplicate `@param` so docs show code example.

docs(api): ensure example code appears in docs for addFeatures

---

packages/arcgis-rest-request/src/utils/ArcGISRequestError.ts
packages/arcgis-rest-request/src/utils/check-for-errors.ts
packages/arcgis-rest-request/test/mocks/errors.ts
packages/arcgis-rest-request/test/utils/ArcGISRequestError.test.ts
packages/arcgis-rest-request/test/utils/check-for-errors.test.ts

Two commits:
- check for errors function: throw an error for a response with a `failure` status
- ArcGISRequestError: In the case that null or an empty string is passed to the constructor, replace with UNKNOWN_ERROR or UNKNOWN_ERROR_CODE
Pretty minor edge cases that I doubt others will encounter, but shouldn't hurt to handle them.

Minor error handling fixes

---

packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-users/src/users.ts
packages/arcgis-rest-users/test/mocks/responses.ts
packages/arcgis-rest-users/test/users.test.ts

Thought I'd take a stab at this. Not really done-done (I would want to add createNotification and removeNotification) but I would like feedback, especially of the "OMG you did this RONG" variety.

feat(users): add getUserNotifications function

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-common-types/src/group.ts
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-sharing/src/group-sharing.ts
packages/arcgis-rest-sharing/src/helpers.ts
packages/arcgis-rest-sharing/test/access.test.ts
packages/arcgis-rest-sharing/test/group-sharing.test.ts
packages/arcgis-rest-sharing/test/helpers.test.ts
packages/arcgis-rest-users/test/mocks/responses.ts

Previously this used `UserSession.getUser()` and would check to see if the group in question was in the user's array of groups. However, since `UserSession.getUser()` implements a caching strategy, if you created a group and then attempted to share an item to that group, the `getUserMembership` check would return `nonmember` even though the user is actually the owner. More about this general problem is on #309 
While there is some discussion about possibly adding cache-busting to the `getUser()` call, I opted to simply make a call to the group itself, which will return the same info.
I also fixed `isItemSharedWithGroup` where we mutated an `IRequestOptions.params` but then sent that into a subsequent call, which resulted in an unexpected url. We should be careful not to mutate that as …

Rework group membership checking, simplify UserSession.getUser

---

packages/arcgis-rest-groups/src/groups.ts
packages/arcgis-rest-groups/src/index.ts
packages/arcgis-rest-groups/src/notification.ts
packages/arcgis-rest-groups/test/groups.test.ts
packages/arcgis-rest-groups/test/mocks/responses.ts
packages/arcgis-rest-groups/test/notification.test.ts

feat(groups): add createGroupNotification

---

package.json
packages/arcgis-rest-auth/src/ApplicationSession.ts
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-feature-service/src/updateAttachment.ts
packages/arcgis-rest-feature-service/test/attachments.test.ts
packages/arcgis-rest-feature-service/test/features.test.ts
packages/arcgis-rest-feature-service/test/mocks/feature.ts
packages/arcgis-rest-geocoder/src/helpers.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/request.test.ts
packages/arcgis-rest-sharing/test/group-sharing.test.ts
packages/arcgis-rest-sharing/test/helpers.test.ts

> should we be running lint before commits and in CI?
yes! we actually always have been, we just weren't passing through the appropriate `tslint` configuration options in husky's precommit hook. whoops!
* thats fixed now
* manual lint fixes
* adding a step in CI to ensure linting is run there too.
ISSUES CLOSED: #301

chore(lint): make sure *all* the code is linted each commit

---

packages/arcgis-rest-feature-service/src/query.ts

no rouge `;` and correct `queryFeatures` respone

docs(api): bad to good

---

packages/arcgis-rest-request/src/request.ts

fix(:bug:): throw a more helpful error message when FormData or Promise are missing

---

packages/arcgis-rest-request/src/utils/encode-form-data.ts
tslint.json

@dbouwman and i trapped a bug this morning in which `/addResources` complains of an invalid file extension even though the correct name was passed along in the request.
this is because internally we set the name of the `Blob` using the parameter name (which doesn't include a file extension) when it wasn't set previously.
```js
fetch("http://edn.maps.arcgis.com/sharing/rest/community/users/jgravois/info/headshot-pacifier.jpg")
.then(response => response.blob())
.then(image => {
const session = new UserSession({
username: "you",
password: "shhhh"
});
// prior to this fix, this is necessary even though 'name' isn't an actual property of Blobs
// image.name = "headshot.jpg"; 
addItemResource({
id: "guidofitemyouown",
owner: "you",
name: "headshot.jpg", // fileName
resource: image, …
```

fix(item): use fileName parameter to name Blobs when present

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

i went with a regex instead of the if/else block @dpbayer suggested.
ISSUES CLOSED: #329

fix(portal): fetch tokens for rest admin requests to services federated with Portal too

---

docs/acetate.config.js
docs/src/api/_package.html
docs/src/api/index.html

As requested in https://github.com/Esri/arcgis-rest-js/issues/321.
Adds basic script tags to api and package pages.
SRI hash proof of concept https://github.com/COV-GIS/arcgis-rest-js/commit/579636bafebff4f2b352c70863dc5331d5650d5e.
Requesting assistance and/or ideas as how to best create SRI hashes for each min js file when starting up the docs build process.

docs(api): add cdn script tag to docs api page and package pages

---

CHANGELOG.md
README.md
demos/ago-node-cli/package.json
demos/attachments/package.json
demos/batch-geocoder-node/package.json
demos/express/package.json
demos/feature-service-browser/package.json
demos/geocoder-browser/package.json
demos/jsapi-integration/package.json
demos/oauth2-browser/package.json
demos/vue/package.json
package-lock.json
package.json
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-feature-service-admin/package.json
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/package.json

@dbouwman published [`v1.11.0`](https://www.npmjs.com/package/@esri/arcgis-rest-request) to npm successfully last week, but when he hit https://github.com/hypermodules/gh-release/issues/82 it derailed pushing the SHA up to `master`
consider this a _better late than never_ PR.
> note: i added a temporary revlock for `gh-release` too.

manual bump to v1.11.0

---

packages/arcgis-rest-items/src/add.ts
packages/arcgis-rest-items/src/helpers.ts
packages/arcgis-rest-items/src/update.ts
packages/arcgis-rest-items/test/add.test.ts
packages/arcgis-rest-items/test/update.test.ts

Items now support `private` resource items: https://developers.arcgis.com/rest/users-groups-and-items/add-resources.htm. This PR adds a param to the types to support this.

Add "access" param to IItemResourceRequestOptions.

---

packages/arcgis-rest-request/package.json

with every release its _something_...
somehow our publish script bumped `@esri/arcgis-rest-request` long enough to ensure the npm release looks correct and then must have reverted the change.
https://unpkg.com/@esri/arcgis-rest-request@1.12.0/package.json

manually bump request to 1.12.0

---

docs/build-typedoc.js
package-lock.json
package.json
packages/arcgis-rest-items/src/update.ts

ISSUES CLOSED: #347 
extra credit:

chore: dont point TypeDoc at test suite

---

packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-common-types/src/webmap.ts
packages/arcgis-rest-feature-service-admin/src/addTo.ts
packages/arcgis-rest-feature-service-admin/test/addTo.test.ts
packages/arcgis-rest-feature-service-admin/test/mocks/layerDefinition.ts

i threw in a couple typings fixes too.

fix: make it possible to update a service using a layer definition

---

packages/arcgis-rest-common-types/src/item.ts
packages/arcgis-rest-common-types/src/webmap.ts
packages/arcgis-rest-feature-service-admin/src/create.ts
packages/arcgis-rest-items/test/mocks/search.ts

i'm hopeful these are the last typing updates i'll need for pending work in hub.js.

fix: more types for new services/layer definitions

---

packages/arcgis-rest-geocoder/src/suggest.ts

Hoping these are the same docs that drive the online documentation here: https://esri.github.io/arcgis-rest-js/api/geocoder/suggest/

chore(docs): fix suggest docs

---

package.json
packages/arcgis-rest-feature-service/src/add.ts
packages/arcgis-rest-feature-service/src/addAttachment.ts
packages/arcgis-rest-feature-service/src/delete.ts
packages/arcgis-rest-feature-service/src/deleteAttachments.ts
packages/arcgis-rest-feature-service/src/helpers.ts
packages/arcgis-rest-feature-service/src/query.ts
packages/arcgis-rest-feature-service/src/queryRelated.ts
packages/arcgis-rest-feature-service/src/update.ts
packages/arcgis-rest-feature-service/src/updateAttachment.ts
packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-geocoder/src/suggest.ts
packages/arcgis-rest-geocoder/test/geocode.test.ts
packages/arcgis-rest-geocoder/test/helpers.test.ts
packages/arcgis-rest-geocoder/test/suggest.test.ts
packages/arcgis-rest-request/src/index.ts
packages/arcgis-rest-request/src/utils/append-custom-params.ts

if you aren't just passing a string to be geocoded, currently this is how you do it:
```js
geocode({
params: {
address: "123 Main St."
}
})
```
the tweaks here ensure you can do this too
```js
geocode({ address: "123 Main St." })
```
cc/ @gavinr

ensure 'first class citizen' geocode request parameters are passed through

---

packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-geocoder/test/geocode.test.ts
packages/arcgis-rest-geocoder/test/mocks/responses.ts

Implemented a truthy check for an address candidate extent prior to assigning a spatial reference to
the extent object. Also updated tests to account for this change, as well as updated typescrypt
interfaces to work  with the candidate data.
ISSUES CLOSED: #376

fix(geocoder): Geocoder checks for null extent before assigning spatial ref.

---

demos/jsapi-integration/README.md
demos/jsapi-integration/index.html

@esri/jsapi-integration
adding a small tweak to our existing demo to show that it is also straightforward to transition _from_ JSAPI authentication to a rest-js `UserSession`

docs: demo how to retrieve credentials from the jsapi too

---

packages/arcgis-rest-common-types/src/group.ts
packages/arcgis-rest-groups/src/helpers.ts
packages/arcgis-rest-groups/test/crud.test.ts
packages/arcgis-rest-items/test/create.test.ts

fix: access is required when creating a new group

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

fix(:bug:): ensure session.portal url is correct when cred.server contains sharing/rest

---

packages/arcgis-rest-common-types/package.json

to help downstream karma-typescript users sidestep errors when the bundler doesn't find any JavaScript.
ref: https://github.com/ArcGIS/arcgis-clone-js/pull/8
personally i don't see a downside to doing this for **every** package.

chore: include raw /src in common-types npm package

---

packages/arcgis-rest-feature-service/src/decodeValues.ts
packages/arcgis-rest-feature-service/test/mocks/cvdQueryResponse.ts
packages/arcgis-rest-feature-service/test/mocks/fields.ts

fix: ensure decodeValues() isnt derailled by attributes not present in metadata

---

packages/arcgis-rest-feature-service/src/add.ts
packages/arcgis-rest-feature-service/src/delete.ts
packages/arcgis-rest-feature-service/src/update.ts
packages/arcgis-rest-feature-service/test/crud.test.ts

Per https://github.com/Esri/arcgis-rest-js/issues/391

Fix crud param names

---

packages/arcgis-rest-auth/src/generate-token.ts

somehow in #389 i missed that we use `@esri/` for referers in request and `@esri.` in auth. 🤦‍♂️ 	
https://github.com/Esri/arcgis-rest-js/blob/fdae3b64b1f31847489c51d6edeafe150591cc4c/packages/arcgis-rest-request/src/request.ts#L199
https://github.com/Esri/arcgis-rest-js/blob/fdae3b64b1f31847489c51d6edeafe150591cc4c/packages/arcgis-rest-auth/src/generate-token.ts#L35
🎩tip to haoliangyu for the find.

fix(:bug:): use same referer consistently in Node.js applications

---

packages/arcgis-rest-geocoder/src/bulk.ts
packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-geocoder/src/reverse.ts
packages/arcgis-rest-geocoder/src/suggest.ts
packages/arcgis-rest-request/src/index.ts
packages/arcgis-rest-request/src/utils/clean-url.ts
packages/arcgis-rest-request/src/utils/get-portal-url.ts
packages/arcgis-rest-request/test/utils/clean-url.test.ts

halfway toward resolving #398 

add utility method to trim whitespace and trailing slashes from input urls

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-feature-service-admin/src/addTo.ts
packages/arcgis-rest-request/src/utils/get-portal-url.ts
packages/arcgis-rest-routing/src/helpers.ts
packages/arcgis-rest-routing/src/solveRoute.ts

i _think_ this is the last of them.
@esri/arcgis-rest-routing

chore: standardize portal urls passed to auth and routing

---

demos/oauth2-browser/authenticate.html

fixed regex to match in cases where `Keep me signed in` is checked

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

When federated servers are configured, the UI does not enforce lower casing of the federated server
name. This can result in hosted services with UPPERCASE urls. This PR ensures that the user session
works with lower-cased urls, and that regardless of casing of inbound requests, the federated token
cache works correctly.

fix(arcgis-rest-auth): Allow mixed casing of federated server urls

---

packages/arcgis-rest-request/src/request.ts

1. Re-exported `IParams` to solve transpiler complaint from packages/arcgis-rest-request/dist/esm/utils/check-for-errors.d.ts that `IParams` was not available from request.ts
2. Combined response cases in function `request` because 1) they are handled identically, and 2) the "zip" variant doesn't work with arcgis.com (one gets a `status: 400  Format not allowed for this Item Type` error), so it seemed misleading to include it in the `switch` statement.

Reexported IParams and joined fetch common types

---

packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common/package.json
packages/arcgis-rest-feature-service-admin/package.json
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-routing/package.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/package.json

resolves #420 🚬 	
@esri/arcgis-rest-common
@esri/arcgis-rest-routing

chore: pkg.browser > pkg.unpkg

---

packages/arcgis-rest-geocoder/src/bulk.ts

When using `bulkGeocode` in _arcgis-rest-geocoder_ If geocoding returns 0 candidates for a given address, the value returned for that address is:
```
{
"address": "",
"score": 0,
"attributes": { . . . }
}
```
Due to the code assuming the `location` property is present, this results in:
`TypeError: Cannot set property 'spatialReference' of undefined`
in the following line of code:
`address.location.spatialReference = sr;`
A quick way to reproduce this is to try a bulkGeocode that includes a nonsense singleLine like `sldafjsedoifhsoaifhsdoifh`.

bulkGeocode: Add check for undefined location property

---

packages/arcgis-rest-auth/src/ApplicationSession.ts

Thoughts on allowing a developer to include their portal address when creating an `ApplicationSession`?  I find doing the following to be somewhat unintuitive:
```js
const session = new ApplicationSession({
clientId: "abc",
clientSecret: "123"
});
session.portal = 'https://myPortal/arcgis/sharing'
```

Support customizing portal when instantiating ApplicationSession

---

packages/arcgis-rest-auth/src/generate-token.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/params.ts
packages/arcgis-rest-request/test/request.test.ts

* use `@esri/arcgis-rest-js` as the default referer instead of `@esri/arcgis-rest` (don't ask)
* skip declaring an `IHeaders` interface (and just link to MDN instead)
* use a ternary 
* continue to set the default `referer` in Node.js applications unless a different `referer` is provided explicitly
* add another test to confirm ^^

proposed tweaks to #436

---

docs/generate-srihashes.js
docs/src/srihashes.json

@COV-GIS's PR worked like a charm.
https://esri.github.io/arcgis-rest-js/api/
this is just a small change to ensure we use the version specified in the lerna.json file.

use lerna.json to increment sri version

---

packages/arcgis-rest-request/src/request.ts

when we landed #437 i did some cursory testing that proved that in the browser native fetch would ignore attempts to set a referer header.
today @benstoltz learned that the custom fetch implementation we use in ArcGIS Hub isn't so forgiving.

fix(:bug:): dont set referer to null in browser apps

---

packages/arcgis-rest-request/src/utils/append-custom-params.ts
packages/arcgis-rest-request/test/utils/append-params.test.ts
packages/arcgis-rest-request/test/utils/process-params.test.ts

fix(:bug:): ensure that custom headers arent misidentified as request parameters

---

packages/arcgis-rest-items/src/get.ts
packages/arcgis-rest-items/test/get.test.ts
packages/arcgis-rest-items/test/mocks/item.ts

caught a few problems with the sample response in the official REST doc page and reported them along the way.

feat: add getItemGroups() function to items package

---

karma.conf.js
packages/arcgis-rest-feature-service-admin/src/create.ts
packages/arcgis-rest-feature-service-admin/test/create.test.ts
packages/arcgis-rest-feature-service-admin/test/mocks/move.ts
packages/arcgis-rest-feature-service-admin/test/mocks/service.ts

If creating a feature service or adding layers &| tables to it fails with an HTTP 400 error, the createFeatureService function doesn't respond with a `resolve` or `reject`, preventing the calling program from resolving the Promise returned by the function.

Modified feature service creation to handle HTTP 400 errors

---

packages/arcgis-rest-sharing/src/group-sharing.ts
packages/arcgis-rest-sharing/test/group-sharing.test.ts

org admins can indeed use [Share Item (as Group Admin)](https://developers.arcgis.com/rest/users-groups-and-items/share-item-as-group-admin-.htm) to share a public item _outside_ their organization with a private group _inside_ their org.
this is true even if they are not a group member/admin.
ISSUES CLOSED: #454

fix: allow org admins to modify group sharing of public items outside the org

---

packages/arcgis-rest-items/src/add.ts
packages/arcgis-rest-items/src/get.ts
packages/arcgis-rest-items/src/helpers.ts
packages/arcgis-rest-items/src/remove.ts
packages/arcgis-rest-items/test/add.test.ts
packages/arcgis-rest-items/test/get.test.ts
packages/arcgis-rest-items/test/mocks/item.ts
packages/arcgis-rest-items/test/remove.test.ts

plowing through old 'to dos' to get our list of open issues down to a single page.
resolves #282

getRelatedItems(), addItemRelationship(), removeItemRelationship()

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

the proposed tweak to `UserSession` would enable developers to build up a UI of their own for users to enter credentials and access secure content from unfederated instances of ArcGIS Server.
```js
import { request } from "@esri/arcgis-rest-request";
import { UserSession } from "@esri/arcgis-rest-auth";
const authentication = new UserSession({
username: "user1",
password: "user1",
server: "https://sampleserver6.arcgisonline.com/arcgis"
});
request('https://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire_secure/MapServer', { authentication })
.then(token)
```
ISSUES CLOSED: #174

feat: new UserSession tied to a non-federated ArcGIS Server instance

---

README.md
demos/stream-response-to-file/.gitignore
demos/stream-response-to-file/README.md
demos/stream-response-to-file/index.js
demos/stream-response-to-file/package-lock.json
demos/stream-response-to-file/package.json
package-lock.json
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/src/fetch-token.ts
packages/arcgis-rest-feature-service-admin/src/create.ts
packages/arcgis-rest-feature-service/src/query.ts
packages/arcgis-rest-feature-service/test/query.test.ts
packages/arcgis-rest-geocoder/src/bulk.ts
packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-geocoder/test/bulk.test.ts
packages/arcgis-rest-geocoder/test/geocode.test.ts
packages/arcgis-rest-sharing/src/group-sharing.ts

You can now pass the `rawResponse:true` option to indicate that a function should return the fetch response directly to the client. This is useful for piping the response to a stream.
stream-response-to-file
ISSUES CLOSED: #462

feat(request): adds option to return the raw fetch response

---

demos/attachments/index.html
demos/oauth2-browser-retry/index.html
demos/oauth2-browser/index.html
docs/src/guides/amd-requirejs-dojo.md
docs/src/guides/from-a-cdn.md

polyfill.io v2 is depreciated. And the v2 docs and bundle builder aren't even available anymore. The v2 cdn still works but if a dev wants to add other features or just check out pollyfill.io they'll most likely switch anyway.
The `es5` feature doesn't exist in v3. I believe this what is now the `default` feature.

Switch polyfill.io to v3

---

CHANGELOG.md
packages/arcgis-rest-auth/README.md
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/README.md
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-common/package.json
packages/arcgis-rest-feature-service-admin/package.json
packages/arcgis-rest-feature-service/README.md
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/README.md
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-groups/README.md
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/README.md
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/README.md
packages/arcgis-rest-request/package.json
packages/arcgis-rest-routing/package.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/package.json

@skitterm aptly pointed out that i removed `IGeocodeParams` in `v1.17.0`.
https://github.com/Esri/arcgis-rest-js/commit/fb2ba9ac2ccaf6ed17e02ecb170009b68f638b00#diff-094efe5f622403522c0543b08434e397
just because we weren't actually utilizing the interface in any of the geocoding methods doesn't mean other developers weren't using it.
whoops!
this PR just adds a note to the CHANGELOG as breadcrumb. while i was in there i bumped the copyright year and added keywords to our package.json files to fix this 😢

re-export IGeocodeParams (until v2.0.0)

---

docs/acetate.config.js
docs/src/api/_declaration.html
docs/src/js/nav-toggle.js
package-lock.json
package.json
packages/arcgis-rest-auth/package-lock.json
packages/arcgis-rest-feature-service/package-lock.json
packages/arcgis-rest-geocoder/package-lock.json
packages/arcgis-rest-groups/package-lock.json
packages/arcgis-rest-items/package-lock.json
packages/arcgis-rest-request/package-lock.json
packages/arcgis-rest-sharing/package-lock.json
packages/arcgis-rest-users/package-lock.json

This PR proposes some of the changes I suggested in https://github.com/Esri/arcgis-rest-js/issues/137#issuecomment-393362439.
1. On pages for functions like `createItem`
2. Where there is a function param called `requestOptions`
3. Print a table under "Options" with all the properties of the type of `requestOptions`.
Then to add some more value
1. where the return type is a known declaration (i.e. something we have defined) in the library somewhere OR
2. A promise that resolves to 1
3. Print a table under "Returns" with all the properties of the type of the object.
This makes pages like `createItem` MUCH more useful since you can now reference all the options AND the return values on 1 page mostly resolving @dbouwman's issues in https://github.com/Esri/arcgis-rest-js/issues/137#issuecommen …

Doc Optimization

---

packages/arcgis-rest-groups/src/create.ts
packages/arcgis-rest-groups/src/helpers.ts
packages/arcgis-rest-groups/src/update.ts
packages/arcgis-rest-groups/test/crud.test.ts
packages/arcgis-rest-items/src/helpers.ts
packages/arcgis-rest-items/test/create.test.ts
packages/arcgis-rest-items/test/update.test.ts

it dawned on me when i submitted #474 that the custom logic we have for serializing groups and items isn't even needed.
the only thing going on in there thats worth keeping is stuffing `item.data` into a `text` parameter.

fix: deprecate serializeGroup() and simplify SerializeItem()

---

demos/oauth2-browser-retry/authenticate.html
demos/oauth2-browser/authenticate.html

an astute developer from the Netherlands pointed out this morning that our browser OAuth demo throws an error when you choose an inline redirect.
this was because the `cleanUrl()` utility function lives inside the request package.
@esri/arcgis-rest-demo-vanilla

docs: resolve inline redirect sample error

---

docs/src/api/_declaration.html
docs/src/api/_layout.html
packages/arcgis-rest-auth/src/UserSession.ts

1. remove the redundant text from the API reference TOC
2. add code snippets to show how to rehydrate a UserSession and make use of its `server` constructor option less opaque.
3. remove the duplicate options tables.
4. remove `server` from [`IOauth2Options`](https://esri.github.io/arcgis-rest-js/api/auth/IOauth2Options/) entirely. i don't _think_ this is a breaking change because it is a nonsensical parameter for that interface that we weren't doing anything with.

chore: miscellaneous doc improvements

---

packages/arcgis-rest-auth/src/get-user-url.ts
packages/arcgis-rest-auth/src/index.ts
packages/arcgis-rest-auth/test/getUserUrl.test.ts

when @tomwayson suggested this initially in https://github.com/Esri/hub.js/pull/144/files#r266006506 i should have known that he likely already considered the circular dependency my own idea would have involved.
this is of course a **perfect** opportunity to use an arrow function, but doing it that way causes two descriptions to be rendered in our doc for some reason.
```ts
export const getUserUrl = (session:UserSession) => `${getPortalUrl(session)}/community/users/${encodeURIComponent(session.username)}`;
```

add new getUserUrl() method to auth package

---

.travis.yml

right now we're force pushing on `gh-pages` every time a commit hits `master`.
https://docs.travis-ci.com/user/deployment/pages/

preserve commit history of the documentation site

---

packages/arcgis-rest-request/src/utils/get-portal.ts

the extra asterisk causes this:

fix typo in code snippet

---

packages/arcgis-rest-groups/src/helpers.ts
packages/arcgis-rest-groups/src/index.ts
packages/arcgis-rest-groups/src/join.ts
packages/arcgis-rest-groups/src/protect.ts
packages/arcgis-rest-groups/test/crud.test.ts
packages/arcgis-rest-groups/test/join.test.ts
packages/arcgis-rest-groups/test/notification.test.ts
packages/arcgis-rest-groups/test/protect.test.ts

made some tweaks to simplify protect/unprotect and make it more evident to TypeScript users that passing authentication is mandatory.

feat: new joinGroup and leaveGroup methods

---

packages/arcgis-rest-items/src/add.ts
packages/arcgis-rest-items/src/helpers.ts
packages/arcgis-rest-items/test/add.test.ts
packages/arcgis-rest-items/test/update.test.ts

this PR can be considered an amendment to #475.
there's no need for item methods to stringify parameters, `request()` handles this internally.

fix: dont stringify values in item calls

---

demos/tree-shaking/README.md
demos/tree-shaking/index.html
demos/tree-shaking/package-lock.json
demos/tree-shaking/package.json
demos/tree-shaking/src/index.js
demos/tree-shaking/webpack.config.js
package-lock.json
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common/package.json
packages/arcgis-rest-feature-service-admin/package.json
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-routing/package.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/package.json

i had a chat with @adamdbradley today 🎩 and he clued me in that consumers will have more luck tree-shaking our ES modules if TypeScript targets something newer than `es5` during compilation.
i don't see a downside to this change because i'd expect those consumers to understand that they have to bring their own transpiler to the party anyway.
```console
$ npx webpack
Hash: 2510a60b03d53bb95c2d
Version: webpack 4.29.6
Time: 1324ms
Built at: 03/15/2019 4:11:26 PM
Asset      Size  Chunks             Chunk Names
bundle.js  1.77 KiB       0  [emitted]  main
Entrypoint main = bundle.js
```
instead of
```console
$ npx webpack
Hash: df51c4225df7f519cb88
Version: webpack 4.29.6
Time: 1183ms
Built at: 03/15/2019 4:20:00 PM
Asset      Size  Chunks             Chunk Names
bundle.js  6.53 KiB       0 …
```

add webpack demo app to show how to tree shake out only the methods in use

---

packages/arcgis-rest-items/src/update.ts
packages/arcgis-rest-items/test/update.test.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/encode-form-data.ts
packages/arcgis-rest-request/src/utils/process-params.ts
packages/arcgis-rest-request/test/utils/process-params.test.ts

i hate to suggest we add this, but i have confirmed @ssylvia's report in #499 
[`/updateResources`](https://developers.arcgis.com/rest/users-groups-and-items/update-resources.htm) is indeed misconfigured and currently only honors requests constructed with FormData (even when the parameters passed don't require it).
to make things worse, the endpoint returns `{ success: true }` regardless.
```js
arcgisRest.updateItemResource({
id: "fe8",
name: "logo.png",
private: true,
authentication
})
.then(response)
```
until the issue is resolved (hopefully in June), my best idea is ~~to inject an undocumented `IParam` that triggers the use of FormData regardless of the input parameters and then strip it out before the request is sent.~~ to insert a little more logic inside `request` that ensures …

fix: force updateItemResource to use FormData

---

demos/vue/src/components/App.vue
demos/webmap-checker-sapper/package.json
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/utils/ArcGISAuthError.test.ts

tl:dr: _super_ edge case fix.
---
in Hub land we started encountering errors when passing a valid (www.arcgis.com) authentication session to _public_ services hosted by unfederated instances of ArcGIS Server.
because of this currently we're sending a whole lot of anonymous requests _after_ users authenticate and using retry() to tack on a session we had the whole time whenever we encounter an `ArcGISAuthError` (see https://github.com/Esri/ember-arcgis-server-services/pull/46 for more info).
it'd be a whole lot nicer to invert the flow and pass through the authentication we have consistently and `catch` the ones that are public, but unfederated.
this PR would allow us to do that, by ensuring that the original `url` and `options` are passed through.
```js
const url = …
```

make it possible for retry() to strip an invalid session

---

packages/arcgis-rest-items/src/get.ts
packages/arcgis-rest-items/test/get.test.ts

fix: catch err internally when getItemData doesnt find any

---

packages/arcgis-rest-items/src/add.ts
packages/arcgis-rest-items/src/helpers.ts
packages/arcgis-rest-items/test/add.test.ts

Resources can be added with just text content, so the resource parameter should be optional.
@jgravois Making `resource` optional means that `IItemResourceAddRequestOptions` is not necessary, so I marked it as deprecated. Let me know if that makes sense.

fix(add resource): make resource an optional parameter

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/src/fetch-token.ts
packages/arcgis-rest-auth/src/generate-token.ts
packages/arcgis-rest-auth/test/generateToken.test.ts

see https://github.com/Esri/arcgis-rest-js/pull/264#discussion_r208381410 for more info.

deprecate passing raw params to fetchToken/generateToken

---

packages/arcgis-rest-geocoding/src/bulk.ts
packages/arcgis-rest-geocoding/src/geocode.ts
packages/arcgis-rest-geocoding/src/helpers.ts
packages/arcgis-rest-geocoding/src/reverse.ts
packages/arcgis-rest-geocoding/src/suggest.ts
packages/arcgis-rest-geocoding/test/mocks/responses.ts
packages/arcgis-rest-routing/src/helpers.ts
packages/arcgis-rest-routing/src/solveRoute.ts

up until now, i wrote a `IBulkGeocodeResponse` interface, but never bothered to declare that `bulkGeocode()` returns it. whoops!
@esri/arcgis-rest-geocoding
@esri/arcgis-rest-routing
BREAKING CHANGE:
IGeocodeRequesttOptions is now IGeocodeOptions, IBulkGeocodingRequestOptions is now
IBulkGeocodeOptions

refactor: remove the word Request from custom geocoding RequestOptions

---

packages/arcgis-rest-feature-layer/src/add.ts
packages/arcgis-rest-feature-layer/src/addAttachment.ts
packages/arcgis-rest-feature-layer/src/decodeValues.ts
packages/arcgis-rest-feature-layer/src/delete.ts
packages/arcgis-rest-feature-layer/src/deleteAttachments.ts
packages/arcgis-rest-feature-layer/src/getAttachments.ts
packages/arcgis-rest-feature-layer/src/getLayer.ts
packages/arcgis-rest-feature-layer/src/helpers.ts
packages/arcgis-rest-feature-layer/src/query.ts
packages/arcgis-rest-feature-layer/src/queryRelated.ts
packages/arcgis-rest-feature-layer/src/update.ts
packages/arcgis-rest-feature-layer/src/updateAttachment.ts
packages/arcgis-rest-feature-layer/test/crud.test.ts
packages/arcgis-rest-feature-layer/test/query.test.ts

@esri/arcgis-rest-feature-layer
BREAKING CHANGE:
Options interfaces in @esri/arcgis-rest-feature-layer have been renamed

refactor(interfaces): removes "Request" from option interface names

---

docs/acetate.config.js
docs/build-typedoc.js
docs/src/_layout.html
docs/src/api/_declaration.html
docs/src/api/_layout.html
docs/src/api/_package.html
docs/src/api/index.html
docs/src/js/api-search.js
docs/src/sass/style.scss
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-portal/src/groups/join.ts
packages/arcgis-rest-portal/src/groups/notification.ts
packages/arcgis-rest-portal/src/groups/protect.ts
packages/arcgis-rest-portal/src/groups/remove.ts
packages/arcgis-rest-portal/src/groups/update.ts
packages/arcgis-rest-portal/src/sharing/group-sharing.ts
packages/arcgis-rest-portal/src/users/get-user.ts
packages/arcgis-rest-portal/src/users/invitation.ts
packages/arcgis-rest-portal/src/users/notification.ts
packages/arcgis-rest-portal/src/users/update.ts
packages/arcgis-rest-request/package.json
packages/arcgis-rest-routing/src/solveRoute.ts
packages/arcgis-rest-types/package.json

Resolves the following in https://github.com/Esri/arcgis-rest-js/issues/518
This also fixes a lot of other small case:
* Tables with long strings now simply scroll left to right (see `UserSession`)
* Each package now includes a sample ES 6 import statement. By default this is all classes and functions but can be customized with a custom `esri.keyExports` field in `package.json` of each package (See `-request`, `-auth` and `-types`)
* Add a blacklist for blocking exports like `genericSearch` and `DEFAULT_ARCGIS_REQUEST_OPTIONS`.
* Update calcite web to latest
* General improvements to the information density of each doc page.
@jgravois this wraps up everything in the API ref that ISN'T actually writing doc. I'll do a separate PR for that later to day if you want to review this.

2.0.0 doc improvements

---

docs/acetate.config.js
docs/build-typedoc.js
docs/src/api/_declaration.html
docs/src/sass/style.scss
packages/arcgis-rest-portal/src/util/SearchQueryBuilder.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/with-options.ts

Covers the remaining REST API items for #518 by documenting `SearchQueryBuilder`, `withOptions()` and `setDefaultRequestOptions()` also:
* excludes private methods and properties from all public doc
* Properly handle the `this` type when rendering
* Handles types like `(IItem | IGroup)[]`
* Better handling of generics when rendering params
* Better handling of rest params `...terms: string[]` now renders as `string[] | string`
* Improve table styling
* Improve function signature rendering for constructor and class methods

Doc new methods for v2.0.0

---

packages/arcgis-rest-portal/src/items/add.ts
packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/test/items/add.test.ts

i couldn't resist the urge to deprecate `addItemJsonData` and just ensure that `addItemData` handles _both_ JSON object literals and binary files.
when i dug into this, @tomwayson and i realized that there was a bug in `createItem` and `updateItem` that kept _them_ both from passing through binary files appropriately.
this PR:
1. fixes the bug in `createItem` and `updateItem`
2. deprecates `addItemJsonData` and ensures that remaining method (`addItemData`) handles both. keeping things DRY by calling `updateItem` internally.
i promise i'm done now :smile:

Fix/handle binary data consistently and deprecate addItemJsonData

---

packages/arcgis-rest-portal/src/util/generic-search.ts
packages/arcgis-rest-portal/src/util/search.ts
packages/arcgis-rest-portal/test/items/search.test.ts

fix(search): replace sortDir with sortOrder in ISearchOptions

---

packages/arcgis-rest-portal/src/util/SearchQueryBuilder.ts
packages/arcgis-rest-portal/test/groups/search.test.ts
packages/arcgis-rest-portal/test/items/search.test.ts
packages/arcgis-rest-portal/test/util/SearchQueryBuilder.test.ts

fix: ensure no space is inserted between search fields and terms

---

packages/arcgis-rest-feature-layer/src/add.ts
packages/arcgis-rest-feature-layer/src/delete.ts
packages/arcgis-rest-feature-layer/src/index.ts
packages/arcgis-rest-feature-layer/src/update.ts

needed for https://github.com/Esri/hub.js/pull/156
@esri/arcgis-rest-feature-layer

refactor: props on feature-layer crud responses arent optional

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-portal/src/sharing/group-sharing.ts

[ICredential](https://esri.github.io/arcgis-rest-js/api/auth/ICredential/)'s "credential" link in "Represents a credential object used to access a secure ArcGIS resource."
[shareItemWithGroup](https://esri.github.io/arcgis-rest-js/api/portal/shareItemWithGroup/)'s "group admin" link in "Share an item with a group, either as an item owner, group admin or organization admin."
[unshareItemWithGroupFunction](https://esri.github.io/arcgis-rest-js/api/portal/unshareItemWithGroup/)'s "group admin" link in "Stop sharing an item with a group, either as an item owner, group admin or organization admin."

Fixed Markdown links

---

packages/arcgis-rest-feature-layer/src/getAttachments.ts
packages/arcgis-rest-feature-layer/test/attachments.test.ts

@esri/arcgis-rest-feature-layer

fix: default to GET when fetching attachments

---

packages/arcgis-rest-auth/src/UserSession.ts

This PR extends the logic that @jgravois added in #560 to other ArcGIS Online environments. This is a requirement for us on the Vector Tile Style Editor since we want to be able to edit vector tile styles from other ArcGIS Online environments (like production) when ArcGIS REST JS is used the internal Esri dev environments.
This does this by tweaking the RegEx used to determine if we should short cut federation or not.
Prior to this PR this is how it worked:
1. Check if both the portal and the requested URL were both `*.arcgis.com`
2. Since both the internal environment and production environment are both `*.arcgis.com` short cut federation
3. The token from the internal environment was sent to the production server causing an error.
4. Since the error didn't occur in …

Force federation accross different ArcGIS Online environments

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

@tomwayson @dbouwman I ran into an issue today were a path to an ArcGIS Server instance had uppercase characters in it and it cased an error when the whole URL was lowercased. Since there were previous cases which stated a domain should be lowercased https://github.com/Esri/arcgis-rest-js/pull/417 I split all this functionality out into its own function and added specific tests for it.

Fix issues with path being lowercased during federation

---

packages/arcgis-rest-auth/src/UserSession.ts

Previously it required a slash at the end. Now it works with pound,
question mark and end of string.

Improve discovery of server root when url is for "services" endpoint.

---

demos/express/package-lock.json
demos/tree-shaking-webpack/package-lock.json
demos/vue/package-lock.json
demos/webmap-checker-sapper/package-lock.json
karma.conf.js
package-lock.json
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/src/federation-utils.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-auth/test/federation-utils.test.ts

Fixes https://github.com/Esri/arcgis-rest-js/issues/583 by adding new utility functions (with a heavy amount of testing) for determining if we can short cut federation for all AGOL environments. This also performs additional normalization on URLs when checking if a given server and portal are federated to allow for possibly mismatched https/http in URLs and or some URLs including or not included a trailing slash.

Fixes for federation and shortcutting  federations

---

packages/arcgis-rest-portal/src/groups/get.ts
packages/arcgis-rest-portal/test/groups/get.test.ts

Now respects:
- `joined`
- `memberType`

fix(portal): searchGroupUsers will now respect additional parameters

---

packages/arcgis-rest-geocoding/src/geocode.ts

@esri/arcgis-rest-geocoding
ISSUES CLOSED: #601

fix(geocode): ensure the magicKey property is passed through.

---

packages/arcgis-rest-auth/src/UserSession.ts

Prevent issues with authenticating with standalone server url's that contain trailing slashes
https://github.com/Esri/arcgis-rest-js/issues/604

Ignore trailing slashes in server url

---

packages/arcgis-rest-portal/src/sharing/access.ts
packages/arcgis-rest-portal/test/sharing/access.test.ts

Currently whe sharing a item w/ access public, the library requests `everyone=true&org=true`. Unfortunately, these appear to cancel each other out and the item is not shared at all. The ArcGIS Onlie Home app sets account=true and everyone=true when sharing publicly. This PR follows suit with the Home App.

fix(portal): setting item access to public shares correctly

---

.travis.yml
package-lock.json
package.json
packages/arcgis-rest-types/tsconfig.json

chore(node): support Node 12

---

packages/arcgis-rest-portal/src/groups/get.ts
packages/arcgis-rest-portal/test/groups/get.test.ts

fix(searchGroupUsers func): searchOptions is now an optional parameter

---

packages/arcgis-rest-feature-layer/src/index.ts

Looks like this got forgotten in PR #607 
@esri/arcgis-rest-feature-layer

Export getService for arcgis-rest-feature-layer

---

packages/arcgis-rest-portal/src/util/search.ts

Per AGO documentation, `aggregations.counts` is an array of objects
https://developers.arcgis.com/rest/users-groups-and-items/search.htm#GUID-1C625F8A-4A12-45BB-B537-74C82315759A

aggs counts should be an array

---

package-lock.json
packages/arcgis-rest-portal/src/util/get-subscription-info.ts
packages/arcgis-rest-portal/test/mocks/portal/response.ts
packages/arcgis-rest-portal/test/util/portal.test.ts

Added a Portal `getSubscriptionInfo` method -- essentially the same thing as `getPortal` or `getSelf` but with `/subscriptionInfo` appended to the URL. Needed to access certain properties only available from this endpoint.

Add Portal getSubscriptionInfo fn

---

demos/batch-geocoder-node/package-lock.json
package-lock.json
packages/arcgis-rest-feature-layer/src/query.ts
packages/arcgis-rest-geocoding/src/geocode.ts
packages/arcgis-rest-geocoding/test/geocode.test.ts

Quick Param Updates

---

packages/arcgis-rest-portal/src/sharing/group-sharing.ts
packages/arcgis-rest-portal/src/sharing/helpers.ts
packages/arcgis-rest-portal/test/mocks/items/item.ts
packages/arcgis-rest-portal/test/mocks/users/user.ts
packages/arcgis-rest-portal/test/sharing/group-sharing.test.ts
packages/arcgis-rest-portal/test/sharing/helpers.test.ts
packages/arcgis-rest-types/src/group.ts

- Correct groupMembership enum to include the actual non-member value of 'none'
- Update sharing so that only owners can share/unshare items from shared edit groups
- Update sharing so that item owners can unshare items from groups they are members of
- Update sharing so group owners, group admins, can unshare items they don't own from groups they belong to
@esri/arcgis-rest-types

fix(sharing): correct the item sharing logic to reflect what the api allows

---

packages/arcgis-rest-feature-layer/src/query.ts
packages/arcgis-rest-types/src/webmap.ts

- Just adding the interface updates in this PR
- #645 needs `IStatisticDefinition` to be exported. That isn't done in this PR.
Edit:
Didn't figure out the second part earlier. It's ready [now](https://github.com/maneetgoyal/arcgis-rest-js/tree/export-statistic-definition). Can push after this is reviewed and merged.

Add percentile related properties

---

packages/arcgis-rest-feature-layer/src/query.ts
packages/arcgis-rest-types/src/index.ts
packages/arcgis-rest-types/src/statisticDefinition.ts

- #645 needed `IStatisticDefinition` to be exported by `arcgis-rest-types` so proposing that change.
- Fixes #645

Move IStatisticDefinition to arcgis-rest-types

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
tslint.json

In cases like the ArcGIS Online app switcher the windows of each respective app are opened with `window.open` which sets `window.opener` and `window.opener.parent` to ArcGIS Online. When used with `{popup: false}` this means that when you call `completeOAuth2` after auth happens `window.opener` is still set and the auth assumes you are in a popup workflow.
This PR adds some extra checks:
1. Check that `popup` is true in the options.
2. Check that the handler exists before trying to call it.
This MIGHT be considered a breaking change because up until now we didn't really do anything if you didn't pass `popup` to `completeOAuth2`. it all still worked because didn't really check popup, which is the error here so this could also be considered a bug. 
I think that by adding a default of …

Fix completeOAuth2 for edge case where window is opened from another window.open call

---

packages/arcgis-rest-portal/src/items/get.ts

Perviously we mutated the requestOptions, but this causes issues if the same requestOptions
instance is used in multiple calls - as in the case of long-promise chains orchestrating complex
interactions with the platform.

fix(getItemResources): do not mutate requestOptions in getItemResources

---

packages/arcgis-rest-types/src/statisticDefinition.ts
packages/arcgis-rest-types/src/symbol.ts
packages/arcgis-rest-types/src/webmap.ts

- Fixes https://github.com/Esri/arcgis-rest-js/issues/654
- `enum` names can be changed. Currently went with what seemed more intuitive.
- ~Some breaking changes are possible. For instance:~ See https://github.com/Esri/arcgis-rest-js/pull/656#issuecomment-591798396.
Earlier, we had:
```ts
export interface ISimpleFillSymbol extends ISymbol {
type: "esriSFS";
style?: SimpleFillSymbolStyle;
color?: Color;
outline?: ISimpleLineSymbol; // if outline has been specified
}
// The following is OK for TSC
const sample: ISimpleFillSymbol = {
type: "esriSFS"
}; 
```
But now we have:
```ts
export const enum SymbolType {
SLS = "esriSLS",
SMS = "esriSMS",
SFS = "esriSFS",
PMS = "esriPMS",
PFS = "esriPFS",
TS = "esriTS"
}
export interface ISimpleFillSymbol extends ISymbol {
type: SymbolType.SFS;
style?: …
```

Replace string union types with const enums

---

packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/items/reassign.ts
packages/arcgis-rest-portal/src/sharing/group-sharing.ts
packages/arcgis-rest-portal/src/sharing/helpers.ts
packages/arcgis-rest-portal/test/items/reassign.test.ts

feat(portal): add reassignItem

---

package-lock.json
packages/arcgis-rest-feature-layer/test/attachments.test.ts
packages/arcgis-rest-feature-layer/test/query.test.ts
packages/arcgis-rest-portal/src/groups/add-users.ts
packages/arcgis-rest-portal/src/groups/update-user-membership.ts
packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/sharing/access.ts
packages/arcgis-rest-portal/src/sharing/group-sharing.ts
packages/arcgis-rest-portal/src/users/invitation.ts
packages/arcgis-rest-portal/src/users/notification.ts
packages/arcgis-rest-portal/test/groups/update-user-membership.test.ts
packages/arcgis-rest-portal/test/sharing/group-sharing.test.ts
packages/arcgis-rest-service-admin/test/create.test.ts

Add two new functions and make shareItemWithGroup smarter.
New behavior: 
**Essentially, allow an org_admin to share an item they do not own to an shared edit group**
The platform will allow an `org_admin` to share an item they do not own, to a shared editing group, as long as the owner of the item is a member of said group.
So - if an `org_admin` calls `shareItemWithGroup`, for an item they do not own, and the group is a shared editing group:
- if the item owner is an admin member of the group: 
- we execute the share call 
- if item owner is not in same org as admin
- we throw with instructive message
- if item owner is in 512 groups
- we throw with instructive message
- if the item owner is not a member of the group, 
- we add the member to the group as an admin
- we execute the share …

feat(portal): add updateGroupMembership, isItemSharedWithGroup

---

README.md

Link was incorrect.
updated description to disambiguate this module from service administration, which means different things to different people across the entire REST API

Correct service-admin link and description

---

packages/arcgis-rest-portal/src/sharing/group-sharing.ts

Current Situation
**Given** Admin is trying to share an item to an update group,
**Then** Item Owner must be an admin in that group
**Result** So, the current code promotes Item Owner to group admin if not already group admin.
The problem is that the Item Owner may be the group _owner_, in which case they don't need to be promoted. The fix is to check only if they are a lowly `member`, instead of checking if they are NOT an admin.

Accounting for update group owner

---

RELEASE.md

After re-reading the [lerna docs on fixed mode](https://github.com/lerna/lerna#fixedlocked-mode-default), I _think_ lerna is doing the right thing, in particular:
> When you run lerna publish, if a module has been updated since the last time a release was made, it will be updated to the new version you're releasing.
I think the ones that are not getting updated are the ones that have not been updated and do not depend on any packages that have been updated. For example, I'm in the middle of cutting a release now. The only package w/ changes is arcgis-rest-portal. When I run `npm run release:prepare` w/ the minor option, the only packages whose versions are updated from 2.9.0 to 2.10.0 are arcgis-rest-portal and those that depend on it. The "lower" level packages like arcgis-rest-request …

remove incorrect lerna instructions

---

notes/README.md
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-portal/src/items/add.ts
packages/arcgis-rest-portal/src/items/create.ts
packages/arcgis-rest-portal/src/items/get.ts
packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/src/items/protect.ts
packages/arcgis-rest-portal/src/items/remove.ts
packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-portal/src/items/upload.ts
packages/arcgis-rest-portal/test/items/helpers.test.ts
packages/arcgis-rest-portal/test/items/reassign.test.ts
packages/arcgis-rest-portal/test/sharing/access.test.ts
packages/arcgis-rest-service-admin/src/create.ts

This resolves https://github.com/Esri/arcgis-rest-js/issues/671 and https://github.com/Esri/arcgis-rest-js/issues/667. Doing the following:
1. `UserSession` now can just accept the `token` option and nothing else when working against ArcGIS Online. `token` and `portal` are required for ArcGIS Enterprise. Tokens are assumed to be valid if `tokenExpires` is not passed. Previously this was an error so it is not a breaking change.
2. Since we might not know the `username` for a given `token`, utility methods like `determineOwner()` now user `UserSession.getUsername()`/`UserSession.getUser()` which use `/community/self` to fetch the `username` for the current token. `UserSession.getUser()` has no external changes and `UserSession.getUsername()` is new.
3. `determineOwner()` is now async since …

Add support for unmanaged sessions, async determineOwner

---

packages/arcgis-rest-portal/src/items/get.ts

If item data is empty, the error message is `SyntaxError: The string did not match the expected pattern` in safari.
Please test the issue by the public item:  `38503de66a594dd7a656c72a34c04183`.

getItemData() throws JSON error if data is empty

---

package-lock.json
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/FetchMode.ts
packages/arcgis-rest-request/src/utils/IRequestOptions.ts
packages/arcgis-rest-request/test/request.test.ts

Adds two option to the IRequestOption:
- <s>`fetchMode`: specify the mode to fetch with (cors, no-cors, etc)</s>
- `secureToken`: hides the token of `GET` request in `X-Esri-Authorization` header.
Both options are disabled by default. This could become the default at a major release.
Fixes: #557

Secure token in POST body or auth header

---

packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/IRequestOptions.ts
packages/arcgis-rest-request/test/request.test.ts

- Turns out the sharing API does not support `X-Esri-Authorization` header as part of the `OPTIONS` request which is required by browser for CORS preflight request.
- For browser, we will force the request to use `POST`

Patch hideToken for browser CORS support

---

codecov.yml
package-lock.json
package.json
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

Adds a new check for oauth handler on window.opener, and cleans up previous handler checks.
ISSUES CLOSED: #711

fix(arcgis-rest-auth): enable oAuth from within an IFrame

---

packages/arcgis-rest-portal/src/items/export.ts
packages/arcgis-rest-portal/test/items/export.test.ts

This was an oversight when originally adding exportItem. This method should allow `targetSR` to be either a `string` or an instance of `ISpatialReference`.

Adding support for ISpatialReference to exportItem

---

packages/arcgis-rest-portal/src/items/remove.ts
packages/arcgis-rest-portal/test/items/remove.test.ts

Previous implementation used non-existant /removeRelationship end-point. 
Changed to the correct /deleteRelationship url
ISSUES CLOSED: #739

fix(arcgis-rest-portal): use deleteRelationship not removeRelationship

---

CHANGELOG.md
package-lock.json
package.json
packages/arcgis-rest-auth/package-lock.json
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-feature-layer/package-lock.json
packages/arcgis-rest-feature-layer/package.json
packages/arcgis-rest-geocoding/package-lock.json
packages/arcgis-rest-geocoding/package.json
packages/arcgis-rest-portal/package-lock.json
packages/arcgis-rest-portal/package.json
packages/arcgis-rest-request/package-lock.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-routing/package-lock.json
packages/arcgis-rest-routing/package.json
packages/arcgis-rest-service-admin/package-lock.json
packages/arcgis-rest-service-admin/package.json

Ran into an odd situation where a developer deleted the `package-lock.json` file in the root, and then did a `npm i` and the build would fail with an error about `__spreadArrays` not being exported from `tslib`.
When we put the lock file back, did a new `npm i` it would build. So I started digging...
I ended up bumping `tslib` to `^1.13.0` in all the packages, as there was a mishmash of versions in there, but it still would fail with the same error. I even added a resolution forcing tslib to 1.13.0, and the rollup task would still fail.
Turns out that the issue was `rollup-plugin-typescript2` - the version we were using had a dep on tslib 1.9.3, and (assuming a little here) since we run that via cli, it uses the version of `tslib` in the plugin's `node_modules` folder.
As far as I can …

Ensure updated tslib

---

docs/src/guides/embedded-apps.md
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

Adds static and instance methods to UserSession to support `postMessage` based authentication.
Adds a Guide to docs re: how to work with this
Note: The message types and payloads have been reviewed in internal meetings

FEAT: Add postMessage auth wrappers

---

.travis.yml
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/src/app-tokens.ts
packages/arcgis-rest-auth/src/validate-app-access.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-auth/test/app-tokens.test.ts
packages/arcgis-rest-auth/test/validate-app-access.test.ts

In an upcoming release, the `esri_auth` clear-text cookie will be removed in favor of an encrypted `esri_aopc` cookie that client's can not read.
To get a token from the `esri_aopc` cookie, the app needs to call `/oauth2/platformSelf`, passing in the client_id and redirect_uri of the app for which they want an app-specific token to be issued.
This is exposed as `platformSelf(clientId, redirectUri, portal?) -> {username: "jsmith", token: "aj8csja..."}`
---
If the app has a token from another app (i.e. it is passed auth information via "postMessage") then the app can exchange that token for a token that is specific to the app.
For example - a Dashboard that is iframed into a Hub Site may get passed an `ICredential` via `postMessage`, but that credential contains a token for the Hub …

feat(auth): add functions to help with removal of esri_auth cookie

---

packages/arcgis-rest-portal/src/items/export.ts

We want the option of not setting `layers` in IExportParameters. That will force the /export service to include all the layers in the delivered export.

Make "layers" parameter of IExportParameters optional

---

packages/arcgis-rest-feature-layer/test/mocks/service.ts
packages/arcgis-rest-types/src/webmap.ts

Layers often have a property named `editingInfo`:
```
"editingInfo" : {
"lastEditDate" : 1604943620640
}
```
This PR adds `editingInfo` to `ILayerDefinition`.

Add editingInfo to ILayerDefinition.

---

packages/arcgis-rest-auth/src/app-tokens.ts
packages/arcgis-rest-auth/test/app-tokens.test.ts

Update the recently added `platformSelf` function to send cookies as well as `?f=json` in the url. 
The latter should be a short-term fix as the API should not require it, but currently it will 405 on the OPTIONS pre-flight if that's no in the url as shown

fix: platformSelf to send cookies and append f=json in url

---

demos/oauth2-browser/index.html
packages/arcgis-rest-auth/src/UserSession.ts

Added optional 'popupWindowFeatures' to 'IOAuth2Options'
Adding an optional 'popupWindowFeatures' property to ‘IOAuth2Options’ allows developers to pass
window features to the popup window. This allows a developer to center the popup if desired using
his own calculated offsets. Currently the popup window features are hard coded. This change simply
exposes them to the developer and provides a default (the prior hard coded values) if not supplied.
The ArcGIS JavaScript API already has the feature:
https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-OAuthInfo.html#popupWindowFeatures

feat(UserSession): added optional 'popupWindowFeatures' to 'IOAuth2Opions'

---

package-lock.json
packages/arcgis-rest-auth/src/app-tokens.ts
packages/arcgis-rest-auth/test/app-tokens.test.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/request.test.ts

the `/platformSelf` call is commonly a cross domain request, and needs to send the `esri_aopc` cookie, thus for that specific request we need to ensure that `credential` is set to `include`
Discussion of this solution here: https://github.com/Esri/arcgis-rest-js/pull/778#discussion_r526391636
Also adds verification of the `credential` param in both the `platformSelf` and `request` test suites.
Apparently `prettier` also wanted to format things in `request`... :-/ 
@noahmulfinger / @tomwayson - I can cut a release once CI is green and one of you give this the 👍 
I'd like to get this out so the Urban team can use it next week

fix: ensure platformSelf sends cookie

---

packages/arcgis-rest-auth/src/index.ts

Missed exporting `app-token` functions from the package 🙃

fix: export app-tokens

---

packages/arcgis-rest-auth/src/app-tokens.ts
packages/arcgis-rest-auth/src/index.ts

As it says - export a fn that should have been exported a while back, and add the `expires_in` prop to the `IPlatformSelfResponse`
Also updates the `platformSelf` doc to include an example creating a UserSession from the `platformSelf` response

Small Fixes: Export validateAppAccess, add expires_in to IPlatformSelfResponse

---

docs/src/guides/embedded-apps.md
packages/arcgis-rest-auth/post-message-auth-spec.md

Add a markdown file that holds specs of the postMessage request objects and types

docs(auth): postMessage spec doc

---

docs/src/guides/embedded-apps.md
packages/arcgis-rest-auth/post-message-auth-spec.md
packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

- Ensure `event.source === window.parent`
- no response unless origin and message type are expected
- update guide and spec

fix(arcgis-rest-auth): postMessage internals

---

packages/arcgis-rest-service-admin/test/addTo.test.ts
packages/arcgis-rest-types/src/webmap.ts

It seems that the type of `ITable.id` should be `number` instead of `string`.
See issue: #808 
@esri/arcgis-rest-types
ISSUES CLOSED: #808

Change type of ITable.id to number

---

packages/arcgis-rest-routing/src/originDestinationMatrix.ts

I learned from the product team that `messages` in the origin destination service response has a structure like:
```
{
"messages": [{
"type": 0,
"description": "A message description"
}, {
"type": 50,
"description": "Another message description"
}],
...rest
}
```
Updated the typings to reflect this.

Update Origin Destination Matrix Response Typings

---

packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/src/items/remove.ts
packages/arcgis-rest-portal/test/items/remove.test.ts

- Removes unused request options (e.g. 'prefix')
- Adds support for optional 'deleteAll'

fix(removeItemResource): support correct parameters

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

Addresses an issue where token duration was not honored in oauth flow due to improper \`duration\`
ISSUES CLOSED: #840

Fix UserSession token duration for oauth

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
tslint.json

ISSUES CLOSED: #843
Replaces #845 
Note that there's a linting error when i try to use `options.duration`:
What's the way to do this properly?

fix(UserSession): switch "duration" to "expiration" in IOAuth2Options

---

package-lock.json
packages/arcgis-rest-portal/src/sharing/share-item-with-group.ts
packages/arcgis-rest-portal/test/sharing/share-item-with-group.test.ts

Prepping for Sharing API v 9.2, there is a change that impacts `shareItemsToGroup` when the user doing the sharing is not the owner, but rather an `org_admin`.
Prior to 9.2, the `/content/items/:id/share` endpoint would allow an `org_admin` to share a private item, owned by another user, to a group (item owner must already be a member in said group).
At 9.2. that no longer works; instead we need to use the `/content/users/:ownername/items/:id/share` route, which is what this PR changes
This is an internal change.
Have verified that this works in PROD, as well as test envs.

Admin's share items via user item route

---

packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/services/get-unique-service-name.ts
packages/arcgis-rest-portal/src/services/is-service-name-available.ts
packages/arcgis-rest-portal/test/services/get-unique-service-name.test.ts
packages/arcgis-rest-portal/test/services/is-service-name-available.test.ts
packages/arcgis-rest-service-admin/src/get-service-admin-info.ts
packages/arcgis-rest-service-admin/src/get-view-sources.ts
packages/arcgis-rest-service-admin/src/index.ts
packages/arcgis-rest-service-admin/test/get-service-admin-info.test.ts
packages/arcgis-rest-service-admin/test/get-view-sources.test.ts
packages/arcgis-rest-service-admin/tsconfig.json
packages/arcgis-rest-types/src/service.ts

During work on the Solution.js vNext code, I wrote some functions that should to be in rest-js.
I've broken them into two places:
in arcgis-rest-portal:
- `getUniqueServiceName`
- `isServiceNameAvailable`
- Not sure if these are available on an ArcGIS Server instance, but the key end-point lives at `/portal/<self|id>/isServiceNameAvailable` so I put these in the portal package
in `arcgis-rest-service-admin`
- `getServiceAdminInfo`
- `getViewSources`
I also added some interfaces into the `arcgis-rest-types` package. Those interfaces are very very loose - just enough to make typescript happy for my needs. If someone has cycles, we could expand them
I'm totally open to moving these around, changing signatures etc etc. Just wanted to get this up to start discussions
I also have two more …

Service Name and Service Info Functions

---

.eslintrc.js
.prettierignore
.prettierrc
README.md
demos/.eslintrc.js
docs/.eslintrc.js
docs/build-typedoc.js
package.json
packages/arcgis-rest-portal/src/util/SearchQueryBuilder.ts

Housekeeping:
- add different / more relaxed eslint rules for `/demos` and `/docs`
- add prettier rules into repo vs relying on VSCode defaults
- I have no strong opinions on these rules - they are the VSCode defaults, this just moves them into the repo so people not using VSCode will have the same rules
- remove the `// prettier-ignore` comments in `SearchQueryBuilder.ts` that were causing prettier to remove *all* comments from the file
- remove `SearchQueryBuilder.ts` from the `.prettierignore` file as we've resolved the issue 
- fix minor lint issues in `build-typedoc.js`
- bump prettier to latest version

Update EsLint & prettier configs

---

packages/arcgis-rest-portal/src/util/SearchQueryBuilder.ts

I've found if you try and pass bad / mangled dates to the query builder that it will not resolve the expression and omit the intended expression from the query.  When throwing the warning, it would be nice to draw attention to this case / reason for failure.
bad dates happen... : )

Updates search query builder error message

---

package.json

@MikeTschudi  mentioned that running `npm run build` was slow when all you wanted to do was make sure the build worked... I'd added `build:esm` in another project, and it helped, so I just added it here.

add build:esm for faster build checks

---

.github/workflows/deploy-docs.yml
.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml

Update the PR logic to run:
- on opened PR's that are not draft
- when PR is marked `ready_for_review` (aka not in draft)
- when reopened, or synched (new commits pushed)
Update Doc Deploy to run on all merges to master
Add comments to pre-release-tests.yml

chore: tweak github action triggers

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

- expected: `refreshTokenTTL` is set to 14 days by default
- actual: `refreshTokenTTL` is set at 1 day by default
#842 
follow-up from #849.

refreshTokenTTL fix

---

packages/arcgis-rest-types/src/statisticDefinition.ts

Documentation states "If outStatisticFieldName is empty or missing, the server will assign one."

outStatisticFieldName should be optional

---

packages/arcgis-rest-types/src/webmap.ts

resolves #896
regarding the following types, they are included in the built in tests but they do not appear anywhere in the [documentation](https://developers.arcgis.com/documentation/common-data-types/domain-objects.htm). have they been deprecated since the tests were written? should they even be included in the domain type anymore?
```typescript
/** Description of the domain */
description?: string,
/** Merge policy */
mergePolicy?: string,
/** Split Policy */
splitPolicy?: string
```

Add domain types

---

packages/arcgis-rest-types/src/service.ts

Taken from the response example found here:
https://developers.arcgis.com/rest/services-reference/online/hosted-feature-service.htm
**Questions:**
- I made `adminServiceInfo` non-optional. Do we know if the response always returns `adminServiceInfo`?
- Can we narrow `type` and `status` further down? I'm unsure about all the possible values.
@dbouwman

Improve adminServiceInfo on IServiceInfo type

---

packages/arcgis-rest-auth/package-lock.json
packages/arcgis-rest-portal/package-lock.json
packages/arcgis-rest-portal/src/sharing/share-item-with-group.ts
packages/arcgis-rest-portal/test/sharing/share-item-with-group.test.ts
packages/arcgis-rest-request/package-lock.json
packages/arcgis-rest-types/package-lock.json

ISSUES CLOSED: #917 #882
Verified against PROD API using https://devtopia.esri.com/dc/portal-api-check/blob/master/spec/admin-share-living-atlast-to-own-group.spec.ts#L36

fix(arcgis-rest-portal): admin uses items/:id/share route for items outside their org

---

packages/arcgis-rest-portal/test/groups/update-user-membership.test.ts
packages/arcgis-rest-portal/test/sharing/access.test.ts
packages/arcgis-rest-portal/test/sharing/share-item-with-group.test.ts
packages/arcgis-rest-portal/test/sharing/unshare-item-with-group.test.ts
packages/arcgis-rest-request/src/ApplicationCredentialsManager.ts
packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/src/fetch-token.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/IAuthenticationManager.ts
packages/arcgis-rest-request/src/utils/IRequestOptions.ts
packages/arcgis-rest-request/test/ApplicationSession.test.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts
packages/arcgis-rest-request/test/request.test.ts
packages/arcgis-rest-request/test/utils/ArcGISAuthError.test.ts
packages/arcgis-rest-request/test/utils/check-for-errors.test.ts
typedoc.json

This PR adds extra support for `Invalid token.` errors. When `request` encounters an invalid token it checks if:
1. The `authentication` option `canRefresh` and has `refreshSession`.
2. The error is `498: Invalid token.`
In this scenario we call `e.retry()` calling `refreshCredentials()` to exchange for a fresh token and retry the request with a new token. 
This should handle edge cases where the server thinks a token is invalid but ArcGIS REST JS thinks it is valid OR were ArcGIS REST JS doesn't have an expiration stored for the token.
In order to avoid edge cases where a server continuously responds with `Invalid token` (for example for a resource that a user doesn't have access too) we have an `internalRequest` function which this implements everything EXCEPT the automatic retry logic. …

Automatically refresh session and try again with new token on invalid token errors

---

demos/express-oauth-advanced/server.js
package-lock.json
packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

This should resolve https://github.com/Esri/arcgis-rest-js/issues/660 allowing the `state` param to be passed through for server side auth so you can associate specific clients to specific auth states.

Server side state

---

packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/IRequestOptions.ts

IRequestOptions.signal is passed to fetch()
resolves #810 #114

feat(arcgis-rest-request): add support for AbortSignal

---

packages/arcgis-rest-portal/test/users/update.test.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/utils/ArcGISAuthError.test.ts

Thinking through the final auth changes there might be weird case where `ArcGISAuthError` was thrown but it wouldn't really make sense to retry the request. 
This PR changes things so that `ArcGISAuthError` ONLY fires on 498/499 errors which are the only codes the JS API pays attention to.
Then the automatic retry logic only applies on `ArcGISAuthError` and ignores the code.

Only throw auth error on code 498/499

---

demos/node-typescript-es-modules/package.json

In checking semantic release for `main` noticed this package was not private, and thus was being processed.

chore: make node-esm demo package private so semrel will ignore it

---

packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-portal/package.json

While updating the doc I noticed that 2 of our unpkg paths were incorrect. This will affect people trying to do things like
```html
<script src="https://unpkg.com/@esri/arcgis-rest-feature-service@4.0.0">
```

Fix feature service packge unpkg

---

packages/arcgis-rest-request/src/ApplicationCredentialsManager.ts

user feedback the example on https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/ApplicationCredentialsManager does not work.

update ApplicationCredentialsManager example

---

packages/arcgis-rest-request/src/ApiKeyManager.ts
packages/arcgis-rest-request/src/app-tokens.ts
packages/arcgis-rest-request/src/types/user.ts
packages/arcgis-rest-request/src/validate-app-access.ts

This fixes a few more `@esri/arcgis-rest-auth` references in the docs.

docs: fix references to @esri/arcgis-rest-auth in examples

---

package-lock.json
package.json
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-demographics/package.json
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoding/package.json
packages/arcgis-rest-portal/package.json
packages/arcgis-rest-request/package.json
packages/arcgis-rest-routing/package.json

- Update `devDependencies` and `peerDependencies` to use `^` ranges for in-repo packages
- change release to use `--deps.bump=inherit` and `--deps.release=inherit` which will leave the `^` ranges in the deps intact.
**NOTE**: There is a bug in the backing release package where a `major` release will _not_ maintain the `^`. There is a PR being discussed to address this, and given we don't do breaking changes often, this seems to be a reasonable solution in the near-term.

feat: peer and dev deps keep ranges

---

README.md

Most of the FAQ topics were broken links since the docs/FAQ.md file was removed. Instead forward to the https://developers.arcgis.com/arcgis-rest-js/faq/ FAQ page.

README FAQ update

---

packages/arcgis-rest-portal/src/sharing/share-item-with-group.ts
packages/arcgis-rest-portal/test/sharing/share-item-with-group.test.ts

This issue was resolved in the 3.x code stream by #919 , but was not picked up in the 4.x branch. This applies the same changes to 4.x

fix: resolve cross-org sharing as admin bug

---

demos/oauth2-browser/authenticate.html
demos/oauth2-browser/index.html
package-lock.json
packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts
packages/arcgis-rest-request/test/request.test.ts

This fixes both #995 and #1006.
The root cause of #995 was assuming that query params could not be included in oAuth redirect URIs, when in fact they can be. Any query params in the redirect URI are expected to be placed back on the redirect URI in addition to any oauth query params like `code` and `error`. To resolve this you now must pass `redirectUri` in `completeOAuth2()` like you did in 3.x. This was still documented that was but some demo code committed it. I left the existing code path in for people who leave out `redirectUri`.
To resolve #1006 we now properly set `redirectUri` on the instance of `ArcGISIdentityManager` in `beginOAuth2()`, `completeOauth2()` and `fromToken()` when it is provided. `canRefresh()` now also checks for `redirectUri` since if it isn't defined you cannot …

fix: #995 and #1006, issues with redirect urls

---

packages/arcgis-rest-request/src/job.ts
packages/arcgis-rest-request/src/utils/process-job-params.ts
packages/arcgis-rest-request/test/job.test.ts
packages/arcgis-rest-request/test/mocks/job-mock-fetches.ts

In `static submitJob`, the params passed in will be processed to check if there is a top level array, if so, `JSON.stringify(Array)`. 
Any MultiValue inputs can only be read as a JSON array. We do this before hitting the REST endpoint. Doubled checked with Mark Torrey with an example of his that this does in fact work.

Added Params Preprocessor for GP Mutilvalue Inputs

---

.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml
packages/arcgis-rest-portal/src/items/add.ts
packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-request/src/utils/encode-form-data.ts
packages/arcgis-rest-request/test/utils/encode-form-data.test.ts

This PR addresses the issue https://github.com/Esri/arcgis-rest-js/issues/1033 at rest-js v3. The bug is related to the [form-data](https://github.com/form-data/form-data) library in the node environment. It requires to use an unofficial option to specify the stream length so that the streaming request can end properly (see https://github.com/Esri/arcgis-rest-js/issues/1033#issuecomment-1292016958).
I add a `dataSize` option to the `addItemData()` function so that the user can give a number for the stream data length.
PS: I suspect other functions accepting node ReadStream can have the same issue, but I don't have the availability to verify and fix each API.
PS2: I assume that no more than one stream is used in one API call.
PS3: I have to update the npm version to v7 in CI so that `npm …

fix(arcgis-rest-request): node ReadStream encoding bug at 3.x

---

packages/arcgis-rest-request/src/job.ts
packages/arcgis-rest-request/src/types/job-statuses.ts
packages/arcgis-rest-request/src/utils/process-job-params.ts

@jf990 noticed in https://devtopia.esri.com/ArcGISDevelopers/open-source-and-third-party-doc/issues/656 that if an `@link` doc tag contains a full url, the tag gets rendered on the page and the closing curly brace is part of the url, causing it to 404. 
I'm going to open a separate issue for the Typedoc plugin to handle this better, but in the short term, this is a PR to just remove the @link helper from three full urls. 
I tested this in the demo site and it works as expected. 
Production (https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/JOB_STATUSES)
Demo:

Remove @link tags from complete urls

---

packages/arcgis-rest-feature-service/src/helpers.ts

the applyEdit results include an error object when success === false
see the spec here: https://developers.arcgis.com/rest/services-reference/enterprise/edit-result-object.htm

fix: add error parameter to IEditFeatureResult

---

packages/arcgis-rest-feature-layer/src/delete.ts

objectIds is currently required by the `IDeleteFeaturesOptions` - this should not be the case since you can also use where clauses to delete features.

types(feature-layer): make objectIds optional

---

packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

The unit tests on ubuntu-14 are fairly consistently running into the "off by a few milliseconds" error that is predicted here:
https://github.com/Esri/arcgis-rest-js/blob/367a49c56daa07e09665e43454a80ae6600534f5/packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts#L1164
Examples:
- ![image](https://user-images.githubusercontent.com/209355/211406700-3ce0ecdf-d454-4cba-aa12-b559dc1531c0.png)
- ![image](https://user-images.githubusercontent.com/209355/211406737-82b544bc-fa68-4b5e-9049-fbe18cf6c43e.png)
In general we can get it to work if we keep re-running the unit test, but that's quite time consuming. This PR loosens the unit test so that it will pass more often so we don't have to re-run it as much.

chore: automated unit test timing issue

---

.gitignore
demos/parcel/.gitignore
demos/parcel/index.html
demos/parcel/index.js
demos/parcel/package.json

Parcel v1 [is deprecated](https://www.npmjs.com/package/parcel-bundler). This PR updates our "Parcel" demo to the latest version of Parcel (v2) (by following the [upgrade documentation](https://v2.parceljs.org/getting-started/migration))

chore: updated parcel demo

---

packages/arcgis-rest-request/src/types/user.ts

added the correct social providers:
https://developers.arcgis.com/rest/users-groups-and-items/user.htm#GUID-32113100-DC2C-41AA-924E-08E2CF686B00
#978

fix(arcgis-rest-request): added social providers

---

packages/arcgis-rest-feature-service/src/applyEdits.ts
packages/arcgis-rest-feature-service/src/helpers.ts

Add add/update attachment interfaces for apply edits.
Looking back at `applyEdits` not sure why I didn't include these at the time @patrickarlt. Here they are if you want to add them.

types(feature-service) add/update attachment interfaces for apply edits

---

packages/arcgis-rest-request/src/app-tokens.ts

Mark type and method as `@private` and `@internal` to exclude them from the docs. Was not sure which was needed, as `@private` suggests it's for private class members, where as `@internal` is more generic.
For v3, we had to add these types to the exclude list as tsdoc did not seem to respect `--excludeInternal` or `--excludePrivate` flags

docs: mark platform self related things @private @internal

---

packages/arcgis-rest-places/src/utils.ts
packages/arcgis-rest-places/test/findPlacesNearPoint.test.ts
packages/arcgis-rest-places/test/mocks/nearPoint.mock.ts
packages/arcgis-rest-places/test/mocks/withinExtent.mock.ts
packages/arcgis-rest-places/test/utils.test.ts

The places API will change the response structure for pagination info soon. This fixes REST JS to support both the old and new style responses so we can do a release an have everything ready to go when the change happens.

fix(arcgis-rest-places): update pagination values for latest API

---

packages/arcgis-rest-feature-service/src/helpers.ts

#1043 
These are currently supported in ArcGIS Online hosted feature services, but not in ArcGIS Enterprise. So these are not yet in the [ArcGIS REST API Documentation](https://github.com/Esri/arcgis-rest-js/issues/1043#issuecomment-1357972948) because they are not supported in ArcGIS Enterprise yet. But due to the request in #1043 and also the fact that they are built into other client libraries like the [ArcGIS Maps SDK for JavaScript](https://developers.arcgis.com/javascript/latest/api-reference/esri-rest-support-StatisticDefinition.html#statisticType), we think it's valid to put these types into ArcGIS REST JS.
Because these are not in the REST API documentation yet, I had to look up what are the actual string names. They can be found in the JSON info of a Feature Service layer, for …

fix(arcgis-rest-feature-service): add additional statistic types

---

packages/arcgis-rest-places/src/findPlacesNearPoint.ts
packages/arcgis-rest-places/src/findPlacesWithinExtent.ts
packages/arcgis-rest-places/src/openapi-types.ts
packages/arcgis-rest-places/test/mocks/nearPoint.mock.ts
packages/arcgis-rest-places/test/mocks/withinExtent.mock.ts

Update documentation for places pagination

---

.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml
package-lock.json

Updates to Node 18 and 20 in the automated test suite.
#1138

test: update node versions in tests

---

packages/arcgis-rest-request/src/types/group.ts

The orgId property is missing from the IGroup interface. 
See [https://developers.arcgis.com/rest/users-groups-and-items/group.htm](https://developers.arcgis.com/rest/users-groups-and-items/group.htm)

fix (arcgis-rest-request): add missing orgId property for group

---

packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

fix: removed owningSystemUrl from IServerInfo

---

.github/workflows/manual-release.yml
package-lock.json

This PR adds a test workflow that we can run to do releases manually rather then the weird re-run a failed workflow that we currently do.
Currently setup to do a dry run for testing.

build: add manual workflow

---

.github/workflows/release.yml
RELEASE.md

Updates the GitHub token to use a token that was generated by me and is stored in this repository's repository secrets (project admins see https://github.com/Esri/arcgis-rest-js/settings/secrets/actions). This _should_ allow the automated build to be completed without disabling the branch protection rules, so I also removed that section of instructions from the `RELEASE.md`.

chore: release token

---

packages/arcgis-rest-request/src/request.ts

This updates the check to make sure users aren't passing oAuth 2.0 tokens directly as strings to handle new token types.

fix: update auth warning

---

packages/arcgis-rest-request/src/ArcGISIdentityManager.ts

This link on this page is not working because of the presence of the parenthesis in the link:
https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/ArcGISIdentityManager/

docs(arcgis-rest-request): fix link

---

demos/node-places-api/categoryData.csv
demos/node-places-api/index.js
demos/node-places-api/package.json
demos/node-places-api/tree.json
packages/arcgis-rest-places/src/findPlacesNearPoint.ts
packages/arcgis-rest-places/src/findPlacesWithinExtent.ts
packages/arcgis-rest-places/src/getCategories.ts
packages/arcgis-rest-places/src/getCategory.ts
packages/arcgis-rest-places/src/getPlaceDetails.ts
packages/arcgis-rest-places/test/findPlacesNearPoint.test.ts
packages/arcgis-rest-places/test/findPlacesWithinExtent.test.ts
packages/arcgis-rest-places/test/getCategories.test.ts
packages/arcgis-rest-places/test/getCategory.test.ts
packages/arcgis-rest-places/test/getPlaceDetails.test.ts

- Added an endpoint param for places method in arcgis-rest-places package which allows to override the built in URL.
- Added test cases 
Pending:
comments for TypeDoc

Allow arcgis rest places package to use dev endpoints

---

demos/attachments/index.html
demos/oauth2-browser-retry/index.html
demos/oauth2-browser/index.html

closes #1172
The only usage of polyfill[.]io is in the old v3 demos. Even though generally we are not maintaining those, we think this security issue is big enough to warrent a small change, for those who may stumble on these in the future.
This switches to using the safe cloudflare version instead: https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet

docs: do not use polyfill.io due to a security issue

---

packages/arcgis-rest-feature-service/src/addToServiceDefinition.ts
packages/arcgis-rest-feature-service/src/createFeatureService.ts
packages/arcgis-rest-feature-service/src/helpers.ts
packages/arcgis-rest-feature-service/src/updateServiceDefinition.ts
packages/arcgis-rest-request/src/types/geometry.ts

Removed all references to `arcgis-rest-service-admin`, which is an old package name that was replaced by `arcgis-rest-feature-service`. See here:
- https://github.com/Esri/arcgis-rest-js/pull/930
- https://github.com/Esri/arcgis-rest-js/issues/933

docs: removed references to `arcgis-rest-service-admin`

---

demos/geocoder-browser/README.md
demos/geocoder-browser/index.html
scripts/get-package-json.js
scripts/run-demo-server.js

+ fix #1140
+ fix the readme.md instructions and uri redirect.

fix: geocoder demo on windows #1140

---

packages/arcgis-rest-request/src/utils/IRequestOptions.ts

- The [`ApiKey` class was renamed to `ApiKeyManager` for v4](https://developers.arcgis.com/arcgis-rest-js/release-notes/upgrade-v3-v4/#renamed-classes) but we missed updating this link.
- The [`ApplicationSession` class was renamed to `ApplicationCredentialsManager` for v4](https://developers.arcgis.com/arcgis-rest-js/release-notes/upgrade-v3-v4/#renamed-classes) but we missed updating this link.
This change should fix the dead links on https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-demographics/IRequestOptions/

docs: reference correct classes

---

.github/workflows/deploy-docs.yml
.github/workflows/manual-release.yml
.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml
.github/workflows/release.yml

This fixes these warnings that we're getting from the GitHub Actions:
---
I will update `codecov/codecov-action` in a separate PR because I think that's a bigger change.

chore: use updated github actions

---

package.json

Just for convenience, adds an npm command (`npm run serve`) to run the script that is already here in the repo.

chore: npm serve command

---

packages/arcgis-rest-developer-credentials/src/createApiKey.ts
packages/arcgis-rest-developer-credentials/src/index.ts
packages/arcgis-rest-developer-credentials/src/invalidateApiKey.ts
packages/arcgis-rest-developer-credentials/src/shared/generateApiKeyToken.ts
packages/arcgis-rest-developer-credentials/src/shared/helpers.ts
packages/arcgis-rest-developer-credentials/src/shared/registerApp.ts
packages/arcgis-rest-developer-credentials/src/shared/types/apiKeyType.ts
packages/arcgis-rest-developer-credentials/src/updateApiKey.ts
packages/arcgis-rest-developer-credentials/test/invalidateApiKey.test.ts
packages/arcgis-rest-developer-credentials/test/shared/helpers.test.ts
packages/arcgis-rest-developer-credentials/test/updateApiKey.test.ts

Adds a few things I would like in for Dev and Tech Summit:
* `invalidateApiKey()` this isn't publically documented and has some quirks so it is good to wrap.
* Fix an issue with generating API key tokens. We only need to pass `client_secret` here.
* Clean up some code examples in the docs.

Add invalidateApiKey(), generate API key bug fix, doc updates

---

packages/arcgis-rest-portal/src/items/remove.ts
packages/arcgis-rest-portal/test/items/remove.test.ts

Resolves #780.
This PR adds the `removeItemThumbnail()` function, allowing users to delete an item's thumbnail via a POST request to the ArcGIS REST API.
- Implements `removeItemThumbnail()` in `remove.ts`.
- Adds unit tests in `remove.test.ts` to verify correct API calls and responses.
- Contains documentation with usage examples.
- Ran `npm test` to confirm all tests pass.
Note: This is my first PR to this project. I’m open to any suggestions or feedback!

feat(arcgis-rest-portal): add removeItemThumbnail()

---

packages/arcgis-rest-portal/src/sharing/helpers.ts
packages/arcgis-rest-portal/test/sharing/helpers.test.ts

Resolves #1197.
This PR updates the documentation for the `getUserMembership()` function. The previous docs incorrectly suggested that the function returns a `Promise` resolving to the `GroupMembership` value `"nonmember"`, when actually it returns `"none"`, per the [GroupMembership documentation](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-portal/GroupMembership/).
- Updated the return value description in the `getUserMembership()` documentation in `helpers.ts`, replacing `nonmember` with `none`.
- Updated corresponding comments in `helpers.test.ts`.
- Ran `npm test` to confirm all tests pass.

docs(arcgis-rest-portal): update incorrect documentation for getUserMembership()

---

packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

In the 3.x -> 4.x transition, the structure returned as part of the postMessage auth flow changed. It needs to be shaped like a [Credential](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html) that the JS SDK can use to instantiate an IdentityMgr
Have verified this in Hub

fix: postMessage must send a Credential that is usable by JSSDK

---

packages/arcgis-rest-request/src/utils/IRequestOptions.ts
packages/arcgis-rest-request/src/utils/append-custom-params.ts

`requestOptionsKeys` were not in sync w/ `IRequestOptions`, which caused valid options to be stripped from the options.

fix(arcgis-rest-request): appendCustomParams strips valid options

---

.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml

Node 22 is LTS right now.
https://nodejs.org/en/about/previous-releases

Add node 22 to tests

---

packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/IRequestOptions.ts
packages/arcgis-rest-request/src/utils/append-custom-params.ts
packages/arcgis-rest-request/test/request.test.ts

Resolves the issue raised in https://github.com/Esri/arcgis-rest-js/pull/904#issuecomment-911938760 by adding a `request` option that allows users to override the implementation of `request()` as @patrickarlt suggested.
~~NOTE this is based on the branch from #1212 b/c I need the changes in that branch in order to test locally.~~

feat(arcgis-rest-request): add option to override request function

---

packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

The Hub team is in the process of migrating from ArcGIS REST JS 3.x to 4.x and we discovered a change in the payload that is sent/expected when [passing authentication from a parent app to an embedded app via postMessage](https://esri.github.io/arcgis-rest-js/guides/embedded-apps/). For us, this manifested as a failure to pass authentication from the Hub to an embedded Dashboard, but surprisingly not to an embedded Survey123 application.
 
Furthermore, we consider this change in payload to be a bug, b/c the old payload, an [ICredential](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/ICredential/), was suitable for initiating authentication w/ either ArcGIS REST JS or the Maps SDK for JavaScript, whereas the new payload, an …

fix(arcgis-rest-request): postMessage auth works w/ credential

---

package-lock.json
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/requestConfig.ts
packages/arcgis-rest-request/src/utils/isSameOrigin.ts
packages/arcgis-rest-request/src/utils/sendNoCorsRequest.ts
packages/arcgis-rest-request/test/request.test.ts
packages/arcgis-rest-request/test/utils/isSameOrigin.test.ts
packages/arcgis-rest-request/test/utils/sendNoCorsRequest.test.ts

Add support for no-cors requests when `portalSelf.authorizedCrossOriginNoCorsDomains` is set, and requests are made to the domains listed.
This is a simple porting of the implementation in 3.x, up to 4.x. Utils and related tests were copied directly, and changes in `request` were slightly different, owing to changes in that function from 3.x to 4.x.

feat: support no cors requests

---

package-lock.json
packages/arcgis-rest-request/src/utils/isSameOrigin.ts
packages/arcgis-rest-request/test/utils/isSameOrigin.test.ts

* Fixes a JS error that is observed when `isSameOrigin` is called with a `null` value for it's `url` arg.
Context: Survey views in the Hub application appear to have regressed when [PR-15058](https://github.com/ArcGIS/opendata-ui/commit/63ee661c585c2d6f49606e5af6c6d67dbd6f173a) merged which bumped our `@esri/arcgis-rest-request` dependency from `4.5.1` to `4.7.1`. When this occurs, a JavaScript error is raised from `isSameOrigin` because a value of `null` is being passed as `url`, which is referenced from the survey's Stakeholder Feature Service View. This worked with V3 of RestJS and with `4.5.1`.

fix(arcgis-rest-request): isSameOrigin returns false when url arg is null

---

package-lock.json
packages/arcgis-rest-feature-service/src/query.ts
packages/arcgis-rest-feature-service/test/query.test.ts

This adds support for using `f=geojson` in `queryAllFeatures()` which I missed while reviewing the [original PR](https://github.com/Esri/arcgis-rest-js/issues/1246).
https://github.com/Esri/arcgis-rest-js/issues/1234

feat(arcgis-rest-feature-service): add support for f=geojson to queryAllFeatures()

---

packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/src/types/oauthState.ts
packages/arcgis-rest-request/src/utils/encodeOauthState.ts
packages/arcgis-rest-request/src/utils/getOauthStateId.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

This PR allows for a workaround to avoid #1231. This allows a custom object to be passed as the `state` property in `.beginOauth2()`. If an object is passed the `originalUrl` will not be encoded into the `state`.
```ts
ArcGISIdentityManager.beginOAuth2({
cilentId,
redirectUrl,
state: {
// an empty object will work to remove the originalUrl behavior
}
});
```
Then in order to make `state` a little more useful it is also exposed on the resulting `ArcGISIdentityManager` instance so it can be accessed after the oAuth process is complete.

Fix #1231 by allowing a custom state object to opt out of originalUrl behavior

---

jasmine.json
karma.conf.cjs
package-lock.json
packages/arcgis-rest-basemap-sessions/test/BasemapStyleSession.test.ts
packages/arcgis-rest-basemap-sessions/test/utils/startNewSession.test.ts
packages/arcgis-rest-elevation/test/findElevationAtManyPoints.test.ts
packages/arcgis-rest-elevation/test/findElevationAtPoint.test.ts
vitest.config.js

This PR migrates the elevation tests to Vitest as an example of https://github.com/Esri/arcgis-rest-js/issues/1251
This also makes some changes to reduce console noise in the tests by passing a auth manager instead of a raw token.

chore: migrate elevation tests to ArcGIS REST JS

---

packages/arcgis-rest-request/src/job.ts
packages/arcgis-rest-request/test/job.test.ts
packages/arcgis-rest-request/test/mocks/job-mock-fetches.ts

This PR makes the job tests quieter by disabling polling during the tests to reduce unmatched requests in fetch mock. In a lot of cases I feel like this shouldn't be happening anyway because we have a lot of generic `*` handlers.
This mostly reworks the test to still test the same cases but without the polling that was causing extra requests. This also adds a utility function to create mocks with different ids so we can differentiate requests between test more easily.

chore: make the job tests less noisy

---

jasmine.json
karma.conf.cjs
packages/arcgis-rest-geocoding/test/bulk.test.ts
packages/arcgis-rest-geocoding/test/geocode.test.ts
packages/arcgis-rest-geocoding/test/helpers.test.ts
packages/arcgis-rest-geocoding/test/reverse.test.ts
packages/arcgis-rest-geocoding/test/suggest.test.ts
vitest.config.js

This PR migrates the demographics package tests to Vitest as part of https://github.com/Esri/arcgis-rest-js/issues/1251

chore: migrate arcgis-rest-geocoding package tests to Vitest

---

packages/arcgis-rest-feature-service/src/query.ts
packages/arcgis-rest-feature-service/test/query.test.ts

Fixes #1261 by passing through the authentication object.

fix(arcgis-rest-feature-service): add support for authenticated layers to queryAllFeatures()

---

jasmine.json
karma.conf.cjs
packages/arcgis-rest-feature-service/src/decodeValues.ts
packages/arcgis-rest-feature-service/test/addToServiceDefinition.test.ts
packages/arcgis-rest-feature-service/test/attachments.test.ts
packages/arcgis-rest-feature-service/test/createFeatureService.test.ts
packages/arcgis-rest-feature-service/test/crud.test.ts
packages/arcgis-rest-feature-service/test/decodeValues.test.ts
packages/arcgis-rest-feature-service/test/getAllLayersAndTables.test.ts
packages/arcgis-rest-feature-service/test/getLayer.test.ts
packages/arcgis-rest-feature-service/test/getService.test.ts
packages/arcgis-rest-feature-service/test/getServiceAdminInfo.test.ts
packages/arcgis-rest-feature-service/test/getViewSources.test.ts
packages/arcgis-rest-feature-service/test/helpers.test.ts
packages/arcgis-rest-feature-service/test/query.test.ts
packages/arcgis-rest-feature-service/test/updateServiceDefinition.test.ts
vitest.config.js

This PR migrates the routing package tests to Vitest as part of https://github.com/Esri/arcgis-rest-js/issues/1251

chore: migrate arcgis-rest-feature-service package tests to Vitest
