Esri/arcgis-rest-js

.travis.yml
README.md
demos/express/package.json
demos/geocoder/package.json
demos/vanilla/package.json
docs/FAQ.md
docs/src/_layout.html
docs/src/guides/amd-requirejs-dojo.md
docs/src/guides/browser-authentication.md
docs/src/guides/browserify.md
docs/src/guides/client-server-authentication.md
docs/src/guides/from-a-cdn.md
docs/src/guides/index.md
docs/src/guides/node-app.md
docs/src/guides/packge-overview.md
docs/src/guides/rollup-babel.md
docs/src/guides/server-authentication.md
docs/src/guides/webpack-and-babel.md
docs/src/guides/webpack-and-typescript.md
docs/src/index.html
package-lock.json
package.json
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/package.json
support/deploy-doc-site.js

resolves #19 (except for the saucelabs part)
after we merge #68 and #70 i think we'll be ready to publish to npm.
> note: a repo admin will still have to flip the switch to 'turn on' travis.

add travis config file and bump to 1.0.0

---

.travis.yml

and leave browser tests to SauceLabs (as per #19)

convince Travis to just run the test suite in Node.js

---

.travis.yml

should resolve #88 (don't think we'll know for sure until this lands in `master`)
i've already saved an `access_token` in the Travis dashboard with the appropriate permissions.

let travis deploy the doc site

---

notes/README.md

mostly for me next time (or @tomwayson)

add release instructions

---

umd-base-profile.js
umd-production-profile.js

currently, **all** the copyright statements from the raw source make their way into the minified output for each package.
https://unpkg.com/@esri/arcgis-rest-request@1.1.2/dist/umd/arcgis-rest-request.umd.min.js
```js
/* @esri/arcgis-rest-request - v1.1.2 - Wed May 02 2018 13:58:50 GMT-0700 (PDT)
* Copyright (c) 2018 Environmental Systems Research Institute, Inc.
* Apache-2.0 */
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports):"function"==typeof define&&define.amd?define(["exports"],t):t(e.arcgisRest=e.arcgisRest||{})}(this,function(e){"use strict";var t=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])};var r=Object.assign||function(e){for(var …
```

chore(copyright): remove duplicate copyright statements from minified built files

---

packages/arcgis-rest-feature-service/src/features.ts

docs(feature-service): add missing `@params`

---

.gitignore
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/request.test.ts

chore(404): new bit.ly link in err message

---

demos/ago-node-cli/package-lock.json
demos/batch-geocoder-node/package-lock.json
demos/express/package-lock.json
demos/feature-service-browser/package-lock.json
demos/geocoder-browser/package-lock.json
demos/oauth2-browser/package-lock.json
demos/vue/package-lock.json
packages/arcgis-rest-auth/README.md
packages/arcgis-rest-feature-service/README.md
packages/arcgis-rest-geocoder/README.md
packages/arcgis-rest-groups/README.md
packages/arcgis-rest-items/README.md
packages/arcgis-rest-request/README.md
packages/arcgis-rest-sharing/README.md
packages/arcgis-rest-sharing/package-lock.json
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-sharing/src/index.ts
packages/arcgis-rest-sharing/src/sharing.ts
packages/arcgis-rest-sharing/test/mocks/sharing.ts
packages/arcgis-rest-sharing/test/sharing.test.ts
packages/arcgis-rest-sharing/tsconfig.json

supercedes #202 
more or less a straight port from Emberland.
```js
setItemAccess({
id: "47f07",
access: "org", // "public" | "private"
owner: "c@sey",
authentication: session
})
.then(response => console.log(response))
```

new sharing module with setAccess() method that includes error trapping

---

docs/src/_layout.html

update boilerplate text in <meta> tag that powers sharing text

---

README.md
docs/acetate.config.js
docs/build-typedoc.js
docs/src/index.html
notes/README.md
packages/arcgis-rest-users/src/users.ts
support/publish.sh

chore(:nail_care:): fixes for broken links mostly

---

demos/ago-node-cli/package-lock.json
demos/batch-geocoder-node/package-lock.json
demos/express/package-lock.json
demos/feature-service-browser/package-lock.json
demos/geocoder-browser/package-lock.json
demos/oauth2-browser/package-lock.json
demos/vue/package-lock.json
package-lock.json
package.json

rev lock karma-coveralls

---

package-lock.json
package.json

to resolve security vulnerability

bump karma to 2.0.2

---

packages/arcgis-rest-geocoder/README.md
packages/arcgis-rest-geocoder/src/bulk.ts
packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-geocoder/src/reverse.ts
packages/arcgis-rest-geocoder/src/suggest.ts

docs(:book:): add link to first external user project

---

umd-base-profile.js

```js
/* @preserve
* @esri/arcgis-rest-request - v1.6.0 - Fri Jul 27 2018 15:13:03 GMT-0700 (PDT)
* Copyright (c) 2017 - 2018 Environmental Systems Research Institute, Inc.
* Apache-2.0
*/
```
becomes
```js
/* @preserve
* @esri/arcgis-rest-request - v1.6.0 - Apache-2.0
* Copyright (c) 2017-2018 Esri, Inc.
* Fri Jul 27 2018 15:13:03 GMT-0700 (PDT)
*/
```

just Ezree in the copyright slug

---

packages/arcgis-rest-users/src/get.ts
packages/arcgis-rest-users/src/index.ts
packages/arcgis-rest-users/src/notification.ts
packages/arcgis-rest-users/test/get.test.ts
packages/arcgis-rest-users/test/mocks/responses.ts
packages/arcgis-rest-users/test/notification.test.ts

chore: break user source and tests out into individual files

---

package-lock.json
package.json

that _was_ easy.
ISSUES CLOSED: #265

chore(tsc): upgrade typescript to v3.x.0

---

.travis.yml

used the travis cli to encrypt the slack token:
`travis encrypt "esri-webgis:SUPER-SECRET-TOKEN-HERE" --add notifications.slack`

chore: send travis notifications to slack

---

package-lock.json
package.json

this will either solve the problem @dbouwman encountered when he did the release dance or at a minimum throw a more helpful error.

bump gh-release@3.4.0

---

demos/oauth2-browser/README.md

@esri/arcgis-rest-demo-vanilla

docs(oauth2-browser): make demo directions for creating an application more specific

---

docs/src/guides/browser-authentication.md

addresses https://github.com/Esri/arcgis-rest-js/issues/315#issuecomment-428699453

docs: make links to external auth doc more prominent

---

CONTRIBUTING.md
README.md
package-lock.json
package.json
packages/arcgis-rest-auth/README.md
packages/arcgis-rest-auth/package.json
packages/arcgis-rest-common-types/README.md
packages/arcgis-rest-common-types/package.json
packages/arcgis-rest-feature-service-admin/README.md
packages/arcgis-rest-feature-service-admin/package.json
packages/arcgis-rest-feature-service/README.md
packages/arcgis-rest-feature-service/package.json
packages/arcgis-rest-geocoder/README.md
packages/arcgis-rest-geocoder/package.json
packages/arcgis-rest-groups/README.md
packages/arcgis-rest-groups/package.json
packages/arcgis-rest-items/README.md
packages/arcgis-rest-items/package.json
packages/arcgis-rest-request/README.md
packages/arcgis-rest-request/package.json
packages/arcgis-rest-sharing/README.md
packages/arcgis-rest-sharing/package.json
packages/arcgis-rest-users/README.md
packages/arcgis-rest-users/package.json
support/dev.sh

port of https://github.com/Esri/hub.js/pull/79
ISSUES CLOSED: #342

chore: watch raw source for changes and recompile

---

notes/README.md

fixed spelling

---

demos/vue/package-lock.json
packages/arcgis-rest-common-types/src/item.ts
packages/arcgis-rest-items/test/mocks/item.ts

@esri/arcgis-rest-demo-vue-with-popup
ISSUES CLOSED: #378

fix: add numViews and size properties to IItem

---

packages/arcgis-rest-auth/src/generate-token.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/request.test.ts

If Window is undefined set referer to the same value generate token uses if window is undefined
@jgravois

Add Code to Request.ts to set Referer

---

packages/arcgis-rest-feature-service/src/decodeValues.ts
packages/arcgis-rest-feature-service/src/getLayer.ts
packages/arcgis-rest-feature-service/src/index.ts
packages/arcgis-rest-feature-service/test/getLayer.test.ts

rename getFeatureService() to getLayer()

---

package-lock.json
package.json

lock event-stream@3.3.4

---

packages/arcgis-rest-feature-service/src/add.ts
packages/arcgis-rest-feature-service/src/addAttachment.ts
packages/arcgis-rest-feature-service/src/delete.ts
packages/arcgis-rest-feature-service/src/deleteAttachments.ts
packages/arcgis-rest-feature-service/src/getAttachments.ts
packages/arcgis-rest-feature-service/src/getLayer.ts
packages/arcgis-rest-feature-service/src/query.ts
packages/arcgis-rest-feature-service/src/queryRelated.ts
packages/arcgis-rest-feature-service/src/update.ts
packages/arcgis-rest-feature-service/src/updateAttachment.ts

Per https://github.com/Esri/arcgis-rest-js/issues/403

chore: clean feature service urls

---

README.md
packages/arcgis-rest-auth/README.md
packages/arcgis-rest-common-types/README.md
packages/arcgis-rest-common/README.md
packages/arcgis-rest-feature-service-admin/README.md
packages/arcgis-rest-feature-service/README.md
packages/arcgis-rest-geocoder/README.md
packages/arcgis-rest-groups/README.md
packages/arcgis-rest-items/README.md
packages/arcgis-rest-request/README.md
packages/arcgis-rest-routing/README.md
packages/arcgis-rest-sharing/README.md
packages/arcgis-rest-users/README.md

[![gzip bundle size][gzip-image]][npm-url]
[gzip-image]: https://img.badgesize.io/https://unpkg.com/@esri/arcgis-rest-request/dist/umd/request.umd.min.js?compression=gzip
[npm-url]: https://www.npmjs.com/package/@esri/arcgis-rest-request

add yet another badge

---

demos/oauth2-browser/authenticate.html

ouath2-browser demo: fix redirect for non url root

---

docs/acetate.config.js
docs/generate-srihashes.js
docs/src/api/_package.html
docs/src/api/index.html
docs/src/guides/package-overview.md
docs/src/srihashes.json
package-lock.json
package.json
packages/arcgis-rest-auth/package.json
support/publish.sh

I'm throwing this out there again @jgravois.
I added it as its own `<code>` in the template and config but could replace the CDN as well.

docs(cdn): add sri hashes

---

docs/src/api/_package.html
docs/src/api/index.html
packages/arcgis-rest-items/src/get.ts

i'm blaming this one on @COV-GIS 😉 	
ISSUES CLOSED: #458

docs: ensure doc pages are generated for packages

---

packages/arcgis-rest-geocoder/src/geocode.ts
packages/arcgis-rest-geocoder/src/suggest.ts
packages/arcgis-rest-geocoder/test/suggest.test.ts

no one but @jgravois to blame for this one.
thanks for the 👀 @haoliangyu!
ISSUES CLOSED: #459

fix: remove magicKey from suggest, surface it more prominently in geocode

---

packages/arcgis-rest-common-types/src/index.ts
packages/arcgis-rest-common/src/types/geometry.ts
packages/arcgis-rest-common/src/util/location.ts
packages/arcgis-rest-common/test/location.test.ts
packages/arcgis-rest-routing/src/solveRoute.ts
packages/arcgis-rest-routing/test/solveRoute.test.ts

Add support for elevation z in routing by allow a third number or z value

Support routing with elevation

---

CONTRIBUTING.md
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/test/mocks/errors.ts
packages/arcgis-rest-request/test/utils/ArcGISAuthError.test.ts

ensure failure to generate a token results in an auth err

---

README.md
docs/FAQ.md

inquiring minds want to know!
cc/ @jpeterson

let folks know whos using rest-js

---

packages/arcgis-rest-geocoding/src/bulk.ts
packages/arcgis-rest-geocoding/src/geocode.ts
packages/arcgis-rest-geocoding/src/helpers.ts
packages/arcgis-rest-geocoding/src/reverse.ts
packages/arcgis-rest-geocoding/src/suggest.ts
packages/arcgis-rest-routing/src/helpers.ts
packages/arcgis-rest-routing/src/solveRoute.ts

https://github.com/Esri/arcgis-rest-js/issues/137#issuecomment-484136369

Refactor constants

---

CHANGELOG.md
docs/src/guides/index.md
docs/src/guides/whats-new-v2-0.md

some typo fixes and additional links for the Whats New guide.

add more links to whats new guide doc

---

demos/tree-shaking-rollup/README.md
demos/tree-shaking-rollup/package.json
demos/tree-shaking-webpack/README.md
demos/tree-shaking-webpack/package.json
demos/vue/package.json
package-lock.json
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-request/src/request.ts
packages/arcgis-rest-request/src/utils/check-for-errors.ts

fix(try): try an anonymous request before throwing an auth error

---

packages/arcgis-rest-portal/test/sharing/group-sharing.test.ts

writing this test helped me realize that my bug was in https://github.com/Esri/ember-arcgis-portal-services/

add a confirmItemControl sharing test

---

README.md

Syncing this with https://github.com/Esri/esri-leaflet/pull/1159

Prefer StackOverflow over GIS StackExchange

---

package-lock.json
packages/arcgis-rest-portal/src/groups/get.ts
packages/arcgis-rest-portal/test/groups/get.test.ts
packages/arcgis-rest-portal/test/mocks/groups/responses.ts

feat(portal): searchGroupUsers searches the users in the given group

---

packages/arcgis-rest-portal/src/items/helpers.ts

Added new types listed in https://developers.arcgis.com/rest/users-groups-and-items/relationship-types.htm
cf #648

Added new item relationship types

---

packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-portal/test/items/update.test.ts
packages/arcgis-rest-portal/test/mocks/items/resources.ts

[updateinfo](https://developers.arcgis.com/rest/users-groups-and-items/update-info.htm)

Added function for updateinfo

---

package-lock.json
package.json
packages/arcgis-rest-portal/src/items/add.ts
packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/test/items/add.test.ts

feat: add resourcesPrefix parameter to addItemResource

---

packages/arcgis-rest-portal/src/groups/search.ts
packages/arcgis-rest-portal/src/util/generic-search.ts
packages/arcgis-rest-portal/src/util/search.ts
packages/arcgis-rest-portal/test/groups/search.test.ts
packages/arcgis-rest-portal/test/mocks/groups/responses.ts

Added support for group contents search

---

demos/oauth2-browser/package-lock.json
package-lock.json
packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/util/get-portal-settings.ts
packages/arcgis-rest-portal/test/mocks/portal/settings-response.ts
packages/arcgis-rest-portal/test/util/get-portal-settings.test.ts

feat(arcgis-rest-portal): add getPortalSettings function

---

packages/arcgis-rest-types/src/statisticDefinition.ts

Add the missing "s" in IStatisticDefinition

---

packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/items/export.ts
packages/arcgis-rest-portal/test/items/export.test.ts

Adds support for [exportItem](https://developers.arcgis.com/rest/users-groups-and-items/export-item.htm).

Adding support for export item

---

packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/items/content.ts
packages/arcgis-rest-portal/test/items/content.test.ts
packages/arcgis-rest-types/src/item.ts
packages/arcgis-rest-types/src/webmap.ts

Adds support for fetching [user content](https://developers.arcgis.com/rest/users-groups-and-items/user-content.htm).

Adding Get User Content

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts
packages/arcgis-rest-request/src/index.ts
packages/arcgis-rest-request/src/utils/decode-query-string.ts

- Add additional authentication providers supported by AGOL
- Better query handling when completing sign in.

Minor authentication improvements

---

packages/arcgis-rest-portal/src/groups/invite-users.ts
packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/orgs/notification.ts
packages/arcgis-rest-portal/test/groups/invite-users.test.ts
packages/arcgis-rest-portal/test/orgs/notification.test.ts
packages/arcgis-rest-types/src/user.ts

Tests are modeled after addGroupUsers

Added functions for creating org notifications and inviting members to groups

---

packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-portal/test/items/update.test.ts

Supply item's folder when updating item

---

packages/arcgis-rest-portal/src/items/get.ts
packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/test/items/get.test.ts
packages/arcgis-rest-portal/test/mocks/items/item.ts

getItemInfo can return the raw response as an escape hatch

---

packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/items/get.ts
packages/arcgis-rest-portal/src/util/scrub-control-chars.ts
packages/arcgis-rest-portal/test/items/get.test.ts
packages/arcgis-rest-portal/test/util/scrub-control-chars.test.ts

getItemResource and scrubControlChars functions

---

packages/arcgis-rest-service-admin/src/index.ts
packages/arcgis-rest-service-admin/src/update.ts
packages/arcgis-rest-service-admin/test/mocks/service.ts
packages/arcgis-rest-service-admin/test/update.test.ts

@esri/arcgis-rest-service-admin

feat(service-admin): add updateServiceDefinition method

---

packages/arcgis-rest-request/src/utils/encode-query-string.ts
packages/arcgis-rest-request/src/utils/process-params.ts
packages/arcgis-rest-request/test/utils/encode-query-string.test.ts
packages/arcgis-rest-request/test/utils/process-params.test.ts

Support array of arrays when encoding query strings

---

packages/arcgis-rest-feature-layer/src/applyEdits.ts
packages/arcgis-rest-feature-layer/src/update.ts
packages/arcgis-rest-feature-layer/test/crud.test.ts

Add trueCurveClient to updateFeatures and applyEdits.

Add trueCurveClient to updateFeatures and applyEdits

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

Support ArcGIS Online 9.1 credentials

---

packages/arcgis-rest-geocoding/src/bulk.ts
packages/arcgis-rest-geocoding/src/helpers.ts
packages/arcgis-rest-geocoding/test/bulk.test.ts

fix bulk geocoding url

---

packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-portal/test/items/update.test.ts

fix(updateItemResources): support item resource prefix

---

packages/arcgis-rest-portal/src/items/add.ts

for https://esri.github.io/arcgis-rest-js/api/portal/addItemResource/
Issue:

fix documentation

---

.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml

to see if Firefox is the issue for our automated testing flakiness. #877

Removed Firefox tests from automatic github action

---

packages/arcgis-rest-auth/src/UserSession.ts
packages/arcgis-rest-auth/test/UserSession.test.ts

Add gating to the postMessage handler so it does not return the credential is the token is expired. Instead, it returns an error, that the Identity Manager can handle today (i.e. a JSAPI patch is not required)
A customer ran into this scenario, where they have a Hub site that embeds Dashboards _after_ the site loads. If a user loads the site, leaves the tab open until their session expires, and THEN they open the Dashboard, the Site hands the Dashboard (which is using JSAPI Identity Mgr) an expired credential. The Identity Manager does not expect an expired token so it infinitely loops hitting /generateToken... like _millions of times_ - which was noticed by the ops team, and eventually resulted in this PR
We need to land this quickly, so it can go out with the Hub release on Nov 2nd, …

fix(arcgis-rest-auth): postMessage returns error if session is expired

---

packages/arcgis-rest-geocoding/src/geocode.ts
packages/arcgis-rest-request/src/ApiKeyManager.ts
packages/arcgis-rest-request/src/ApplicationCredentialsManager.ts
packages/arcgis-rest-request/src/ArcGISIdentityManager.ts

Should resolve https://github.com/Esri/arcgis-rest-js/issues/893 pushing the use of the static methods.

Encourage use of static methods in auth doc 

---

packages/arcgis-rest-feature-service/test/mocks/cvdQueryResponse.ts
packages/arcgis-rest-request/src/types/feature.ts

follow up from fc64c99d434ed812c2c09849828a8beec8f106ae (#937) (code from @COV-GIS), getting this code into v4.

fixed IFeature geometry type

---

packages/arcgis-rest-request/src/types/user.ts

Update user.ts to add 'id' property to IUser type definition

Add 'id' property to IUser type definition

---

RELEASE.md

chore: updated release documentation

---

packages/arcgis-rest-portal/src/items/create.ts
packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-portal/test/items/create.test.ts
packages/arcgis-rest-portal/test/items/update.test.ts

bug: create/update items convert extent to string frm bbox

---

packages/arcgis-rest-portal/src/items/create.ts
packages/arcgis-rest-portal/src/items/helpers.ts
packages/arcgis-rest-portal/src/items/update.ts
packages/arcgis-rest-portal/test/items/create.test.ts
packages/arcgis-rest-portal/test/items/update.test.ts

Addresses #1023 for the 4.x version

fix: encode item extent prior to calling request

---

packages/arcgis-rest-request/src/job.ts

typo in job.ts doc

---

packages/arcgis-rest-request/src/job.ts

I assume getAllResults, there is no method getResults

Update job.ts doc

---

README.md
package-lock.json

Added instructions to create new packages. Please feel free to modify to make the steps clearer.

Readme: Added Instructions for creating new packages

---

.github/workflows/pre-release-tests.yml
.github/workflows/pull-request-tests.yml

Removed Node v12 from the automated testing

chore: removed node 12

---

.github/ISSUE_TEMPLATE/documentation.yml
CONTRIBUTING.md

- Cleaned up the `CONTRIBUTING.md` file a bit
- Added a "Documentation" issue template for the community to report issues with the guides/samples.

Documentation issue type

---

packages/arcgis-rest-portal/src/index.ts
packages/arcgis-rest-portal/src/users/get-user-properties.ts
packages/arcgis-rest-portal/src/users/set-user-properties.ts
packages/arcgis-rest-portal/test/mocks/users/user-properties.ts
packages/arcgis-rest-portal/test/users/get-user-properties.test.ts
packages/arcgis-rest-portal/test/users/set-user-properties.test.ts

Issue: [84](https://devtopia.esri.com/dc/hub/issues/84)
Expands arcgis-rest-portal to make user properties accessible.

feat(arcgis-rest-portal): add user properties functions

---

packages/arcgis-rest-request/src/types/geometry.ts

fix(arcgis-rest-request): geometry type esriGeometryMultiPatch

---

packages/arcgis-rest-places/src/findPlacesWithinExtent.ts
packages/arcgis-rest-places/src/getCategory.ts
packages/arcgis-rest-places/src/getPlaceDetails.ts

chore(doc): fix example code

---

packages/arcgis-rest-geocoding/src/bulk.ts
packages/arcgis-rest-geocoding/src/geocode.ts
packages/arcgis-rest-geocoding/test/bulk.test.ts
packages/arcgis-rest-geocoding/test/geocode.test.ts

chore: change postal and postalExt to string

---

demos/batch-geocoder-node/README.md
demos/batch-geocoder-node/batch-geocode.js
demos/oauth2-browser/README.md
packages/arcgis-rest-demographics/README.md
packages/arcgis-rest-feature-service/README.md
packages/arcgis-rest-geocoding/README.md
packages/arcgis-rest-places/README.md
packages/arcgis-rest-portal/README.md
packages/arcgis-rest-request/README.md
packages/arcgis-rest-routing/README.md

fixes #1148
Thanks for your help with that @gavinr-maps !

docs: update links to target the v4 docs

---

packages/arcgis-rest-demographics/src/getAvailableCountries.ts

for the arcgis-rest-demographics package

fix: small change to trigger a catch-up release

---

packages/arcgis-rest-developer-credentials/README.md

adding a readme to this package that lacks one.

fix: change to trigger a catch-up release

---

.github/workflows/manual-release.yml

Fixes our manual release job to actually work.

chore: add manual release option

---

packages/arcgis-rest-request/src/ArcGISIdentityManager.ts
packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts

Pull to alpha branch to deploy and test an alpha release.

fix(arcgis-rest-request): postMessage auth works w/ credential

---

packages/arcgis-rest-request/src/index.ts

bah. Add the export in the index.ts

fix: actually export no-cors utils
